### ISSUE TITLE
Quick Scenario Error

### ISSUE THREAD

**Issue by Adamantcheese** [ryceg/Eigengrau-s-Essential-Establishment-Generator#101]
**Describe the bug**
The quick scenario generator gives errors when Spring/Mountain is selected.

**To Reproduce**
Restart or go directly to the main page, change the quick scenario settings to Spring and Mountain and hit Create Scenario.

**Expected behavior**
A scenario is generated without crashes.

**Error dialog**
Apologies! An error has occurred. You may be able to continue, but some parts may not work properly.

Error: <<set>>: bad evaluation: setup.misc.locations[encounterKey] is not a function.

Stack Trace:
value@https://eigengrausgenerator.com/:31665:3822
handler/<@https://eigengrausgenerator.com/:31666:23466
value/<@https://eigengrausgenerator.com/:31666:8881
t/<@https://eigengrausgenerator.com/:31662:29527
dispatch@https://eigengrausgenerator.com/:63:41720
add/y.handle@https://eigengrausgenerator.com/:63:39774

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 66.0.5
 - Version 2.2.1

**Comment by cktang88** [comment]
This would be in https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/blob/master/EssentialEstablishmentGenerator/World/miscData.js#L3014

**Comment by cktang88** [comment]
"Road" also gives a similar error, see #112

**Comment by cktang88** [comment]
Undefined locations:
- 'an isolated monastery'
- a small cave in the crook of a rock wall
- a peculiar cabin

**Comment by ryceg** [comment]
Thanks for this. Have just commented them out for now, will create the relevant undefined locations & encounters later.
