### ISSUE TITLE
Set up eslint config to be used by all contributors

### ISSUE THREAD

**Issue by monsagri** [ryceg/Eigengrau-s-Essential-Establishment-Generator#105]
**Is your feature request related to a problem? Please describe.**
As far as I can tell, you haven't got a linter set up with this project. I can see an eslintrc.js file, but as you don't have a package.json with the project that includes eslint and the aribnb config you are importing in the dev dependencies, you are relying on each contributor having eslint installed globally. 
Having eslint installed with the project would be really helpful for contributors as well as help the project retain a more uniform codebase.

**Describe the solution you'd like**
The solution would be to add a package.json file which includes eslint and the airbnb-base config, and probably to add some config to the airbnb linter to match your preferred style (for example not enforcing rules about semicolons at the end of lines).
Depending on how opinionated you want to be about coding you might want to set up prettier as well.

**Describe alternatives you've considered**
I can't really think of a sensible alternative that will allow the codebase to maintain consistency as you allow more contributors.

**Additional context**
I've set all this up on my local machine and it works fine. There are a *lot* of linter errors with the current codebase, but luckily a lot of them can be autofixed. 
In fact, this would quite handily take care of [Issue 88](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/issues/88), as you can automatically convert all `var`s to `let`s and all non reassigned `let`s to `const`s without investing a lot of time.

Really love the project and would love to contribute, I will definitely be using the contributor in my homegames.

**Comment by WishingOnAWendy** [comment]
We'll get right on that! Resident code man ryceg is I think in bed for the night so it may take a little while 👍

**Comment by ryceg** [comment]
Ah yes, good idea. I am indeed in bed :P I totally forgot that I had started to set that up, will have to finish the job

**Comment by monsagri** [comment]
I can make a PR for it as well if you'd like, I've got the whole thing setup locally already. 

Obviously depends on whether you want any custom rules etc.

**Comment by ryceg** [comment]
Implemented, therefore closed!
