### ISSUE TITLE
Delete dead (commented out) code

### ISSUE THREAD

**Issue by Glinkis** [ryceg/Eigengrau-s-Essential-Establishment-Generator#109]
**Is your feature request related to a problem? Please describe.**
There have been a lot of great articles written about this subject.
For example:
- [Commented out code is junk](https://blog.submain.com/commented-out-code-junk-codebase/)
- [The danger of commenting out code](https://markhneedham.com/blog/2009/01/17/the-danger-of-commenting-out-code/)
- [Dead code, alive problem](https://dev.to/damnjan/dead-code-alive-problem-15c)

**Real example from the source**
```javascript
propNamesArray.forEach(function (propName) {
  // var propName = propNamesArray[i]
    if (!Object.keys(object).includes(propName)) {
      console.log('No ' + propName + ' roll value! Creating one...')
      console.log({ object })
      object[propName] = random(1, 100)
    }
  // }
})
```

**Describe the solution you'd like**
It would be great if all dead code could be deleted.

**Comment by ryanjmack** [comment]
I'm going to take care of this issue. I'll submit a PR later today!

**Comment by WishingOnAWendy** [comment]
> I'm going to take care of this issue. I'll submit a PR later today!

Ah actually this was addressed elsewhere and this PR was meant to be closed, there is a lot of commented code that needs to be manually shifted through as some things are only temporarily commented out. We are currently doing dead code removal in chunks
