### ISSUE TITLE
Some mountain scenarios are commented out

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#118]
As part of the ongoing efforts to remove dead code, the following entries for the `mountain` object in `miscData.js` need to be either commented out, or have their relevant scenarios created in `/World/locations.js`.

  ```  // 'a peculiar cabin',
    // 'an isolated monastery',
    // 'a remote temple',
    // 'an ancient temple',
    // 'a ruined monastery',
    // 'a small cave in the crook of a rock wall'```

Similarly, the `road` encounter `// 'some raiders'` needs to be removed or hooked up to the raiders function.

**Comment by WishingOnAWendy** [comment]
The mountain scenarios have been added. However errors like `bad evaluation: setup.misc.locations[encounterKey] is not a function`, `contentsTarget[Key] is not a function`, `cannot read property 'seededrandom' of undefined`, and `cannot read property 'includes' of undefined`
need to be addressed I feel before Stable 2.3 release
