### ISSUE TITLE
NPC life events / history should be tied to year, as should the preamble.

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#123]
NPC life events and history are currently somewhat awkward, and read strangely.
![image](https://user-images.githubusercontent.com/36913739/57851699-9413eb80-7824-11e9-9c33-306490d247b3.png)

Recommended course of action: tie life events to dates ("When I was 22", "About four years ago", etc), and add "preamble" or "postamble" phrases to each type of event.

**Comment by WishingOnAWendy** [comment]
Instead of tying them to a specific time period I moved the output to read more like they are simply recalling certain life events in no particular order, if you would still prefer exact dates let me know
