### ISSUE TITLE
Incorporate profession descriptions from Reddit

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#129]
Incorporating profession descriptions from [this](https://redd.it/bmrilt) reddit thread into `professions.js` would be great. Please don't bother to do this tedious and boring task unless you're very very bored and/or can automate it somehow!

**Comment by WishingOnAWendy** [comment]
How would you recommend going about this?

**Comment by azulflame** [comment]
The professions and descriptions have been inserted, but are still missing the Supporting Value and other fields.

**Comment by ryceg** [comment]
Awesome stuff. Closing this issue and creating a new one for Support Values & rest of the data.
