### ISSUE TITLE
Consider not including the built html file in source control

### ISSUE THREAD

**Issue by Glinkis** [ryceg/Eigengrau-s-Essential-Establishment-Generator#130]
In general, a repository should include everything required to build a program, but not the built program itself.

Could we remove the `docs/index.html` file?

**Comment by ryceg** [comment]
Yeah. I'm using GitHub Pages to serve the app (since it's a static website, I figure that there's no reason not to save a buck). I'll shift the built html over to a separate repository, so there's no confusion about what the purpose of this repository is.

**Comment by Glinkis** [comment]
Actually, you could use a separate branch in this repo. There is a utility called [gh-pages](https://www.npmjs.com/package/gh-pages) that does this automatically.

I can set it up if you'd like.

**Comment by ryceg** [comment]
That would be amazing! Thanks so much

**Comment by monsagri** [comment]
Github pages seems like a good shout, but we could also just use the gitignore file for stuff we don't want controleld right?

**Comment by Glinkis** [comment]
Well, I think you'll find that's exactly how it's set up in my pull request.

**Comment by ryceg** [comment]
Pulled and implemented!
