### ISSUE TITLE
Add daily wage, support values, and other missing fields into the new professions that have been added.

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#136]
Example of current data structure: 

```
urchin: {
    sv: 500,
    type: '',
    sector: '',
    description: 'a child who lives or spends most of their time in the streets, occasionally working as a thief or pickpocket.',
    socialClass: '',
    socialClassRoll () { }
  }
```

`sv`: the Support Value, which is the population needed to support one of that profession. A hamlet of fifty has no need for an actor, but they have need for many farmers. The probability of professions is calculated by dividing town.population by the sv value of each profession. A potter might have an sv value of 200, so if there's a town of 300, there will be one potter, and a 50% chance of there being a second.
`type`: describes the type of work; can be 'dndClass', 'labourer' for unskilled work, 'profession' for skilled work, or 'business'.
`sector`: can be 'agriculture', 'construction', 'craftsmanship', 'magic', 'science', 'arts', 'business', 'government and law', 'military', 'outcast', or 'crime'.
`description`: should be a description of the profession.
`socialClass`: Social Class is going to be more important in the future, basically it ensures that relationships develop between the same social levels of society; it would make no sense for an aristocrat to marry a pauper, and a nobleman would not have a peasant for a best friend.
`socialClassRoll`: another way of expressing social class. The index is found in `SetupSocialClass.js`

I should clarify the reasoning behind `socialClass` and `socialClassRoll` being two discrete things, while serving the seemingly same function. Having them as two seperate things allows for specifying `socialClass` and not the profession; when the NPC is searching for a profession, if `socialClass` is defined, it curtails the list of professions to the matching social classes. This is especially useful for maintaining relationship cohesiveness; children will be born into the same social class as their parents.

Missing value:

`dailyWage`: an integer expressed in copper pieces, or a function that outputs an integer expressed in copper.

**Comment by WishingOnAWendy** [comment]
The dailyWage has been added to each profession, but has currently not been changed per profession

**Comment by ryceg** [comment]
each profession's wage has been edited now.
