### ISSUE TITLE
Randomly generated data mostly doesn't work (on a windows surface RT 8.1 tablet with IE11)

### ISSUE THREAD

**Issue by ComedianTF2** [ryceg/Eigengrau-s-Essential-Establishment-Generator#14]
**Describe the bug**

First error is [tw-user-script-0]: syntax error
next: Error [StoryInit]: <<set>>: bad evaluation: Object doesn't support property or method 'createNPC'
next: Error [PassageReady]: <<if>>: Bad conditional expression in <<if>> clause: unable to get property 'sizeroll' of undefined or null reference.

Then on the main page, any name is for example $tavern.road or $tavern.wordnoun, $tavern.name, $tavern.road, $smithy.road $smithy.name, $generalstore.road $generalstore.name, etcetera etcetera.

The name of the city however, does function properly. On the tablet it shows Sangarden, on my PC it shows Icerise

when you go to a specific page, such as the tavern page, you get the same PassageReady error.

Then on that page you have the same issues with names.

However, some of the random generation does seem to work. On my desktop the text goes as such:

If you talk with the bartender, and ask for more, on the PC it says:

'Well...The hedge maze in front of the manor has been maintained for decades by a strange elf who speaks in cryptic riddles. Recently, a visiting noble from a nearby kingdom went into the maze and never came out. Everyone who has gone in looking for him has met the same fate...'

On the RT tablet with IE11:

Well, a talented sculptor recently did a sculpture for the lord of Sangarden and ever since, the lord has not been himself- before he remembered all his servant's names, and now he merely bark orders... we fear that something happened to him.'

That means that there is some of the random generation that is working, but not others.

On the house cheese part:

desktop: The house cheese is 1 Silver 4 Copper and is a warm yellow cheese which is moist and delicious. It smells like a roast duck filled with spices, and tastes sharp.

IE11: the house cheese is (error on the money part here) and is a light green cheese which is moist and delicious. It smells like the ass of a cow in cheese form, and tastes somewhat bland.

Again, part of the randomization here is working, but other parts is not. 

**To Reproduce**
go to any page,

**Expected behavior**
names instead of $a.b

**Screenshots**
![screenshot 1](https://user-images.githubusercontent.com/33683622/41234384-4db3a462-6d8c-11e8-8c26-0711846a328e.png)

**Smartphone (please complete the following information):**
 - Device: Windows RT surface tablet
 - OS: Windows 8.1 RT
 - Browser IE11
 - Version 11.0.9600.19003

**Additional context**
Look, I don't expect you to be able to fix any issues. It's internet explorer. It's windows RT. It's probably only me that's ever gonna be bothered by it, and that's just cause I'm poor and can't afford a new tablet anytime soon. I completely understand, but I'm just hoping these are super easy to fix problems, so who knows! The fact that some things do work makes me hopeful. 

I do plan on supporting you on patreon as soon as I can, but that's gonna happen no matter if you can fix it or not. I can just use my android phone instead of the tablet for this specific use. It's just so amazing!

**Comment by ryceg** [comment]
Hey ComedianTF2, thanks for submitting this bug report, especially considering how detailed it is. Unfortunately, Microsoft haven't implemented ES6 in IE11, and they're not planning on it. IE11 accounts for roughly 1% of my userbase, so it's unlikely that I'll get around to optimising for outdated browsers. I appreciate your support, and will do my best to optimise for mobile (which is more like 50% of users) so you can still use it!
