### ISSUE TITLE
Use correct grammatic terms as variable names

### ISSUE THREAD

**Issue by Glinkis** [ryceg/Eigengrau-s-Essential-Establishment-Generator#159]
For clarity and proper semantics, I suggest naming things after their grammatical terms.

For example, `shopkeep.heshe` would be `shopkeep.subjectPronoun`, `bartender.himherself` would be `bartender.reflexivePronoun`, and `bartender.hisher`would be `bartender.possessivePronoun`.

**Comment by ryceg** [comment]
This is a good point, and is totally semantically correct. However, the reasoning behind the naming convention was to enable people to write _relatively_ plain English. By changing `.heshe` to `.subjectPronoun`, we add another layer of translation to the code, obfuscating what is going on. 

```You enter $blacksmith.name, and see the blacksmith is pouring molten metal into a cast in the far back. $blacksmith.subjectPronoun.toUpperFirst() raises a hand with a wave, and drags $blacksmith.possessivePronoun feet over to you, and introduces $blacksmith.reflexivePronoun as $blacksmith.name, the master smith of the smithy, and asks what $blacksmith.subjectPronoun can do for you.```

While technically correct, the above has lowered code readability. Perhaps more importantly, using correct grammatical terms impede the flow of writing; the aim of the front-facing variables is to allow easy composition of sentences that make grammatical sense with the variable name acting as placeholder data. I haven't articulated this at all in any formal documents, so I'll add this to the wiki to clarify the reasoning.

**Comment by Glinkis** [comment]
All right. That makes a lot of sense. I think we can close this ticket then.
