### ISSUE TITLE
Populate CHANGELOG.md with all recent development changes

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#161]
Haven't been keeping a close enough eye on the changes, so any planned/implemented changes since 2.2 should be put in [CHANGELOG.md](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/blob/master/CHANGELOG.md).

**Comment by Glinkis** [comment]
Maybe using feature branches ,which gets squash-merged would be better? So in the git tree, each commit to master is named `#<pr-number><pr-title>.
