### ISSUE TITLE
Error: "wealth" is undefined

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#174]
Related to the bakeries, florists, and tailor shops' structure getters. Doesn't seem to be correctly passing it.

**Comment by WishingOnAWendy** [comment]
When I see it seems to be directly linking to bakeries

**Comment by ryceg** [comment]
Fixed https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/commit/3567b9faa24ab56d7b95c73552bae772711ba91b
