### ISSUE TITLE
`$tavern.name` displayed when viewing Poisoned Potioner one-shot

### ISSUE THREAD

**Issue by paullessing** [ryceg/Eigengrau-s-Essential-Establishment-Generator#183]
**Describe the bug**
On the "Poisoned Potioner" one-shot page, the tavern name renders as `$tavern.name`.

**To Reproduce**
1. Open Eigengrau's Generator
2. Go to Toolbox
3. Click on "One Shot - Poisoned Potioner"

**Expected behavior**
Generated tavern name should display

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74.0.3729.169 (Official Build) (64-bit)

**Comment by ryceg** [comment]
Ah, I totally forgot about the one-shot. Thanks for the heads up!

**Comment by ryceg** [comment]
Fixed in https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/commit/22a3c55e7cb914c561852f50158a745bf1d9701e
