### ISSUE TITLE
Error when saving town details

### ISSUE THREAD

**Issue by paullessing** [ryceg/Eigengrau-s-Essential-Establishment-Generator#184]
**Describe the bug**
When saving town details, I get an error message:
```
Error: Cannot read property 'tippyDescription' of undefined.
```

**To Reproduce**
Generated a town, edited settings (changed name, feudalist democratic republic, town size=6000). Saved.

**Expected behavior**
Should save successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/6681183/59146483-c6110b80-89e6-11e9-8116-2635720fb140.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 74

**Comment by ryceg** [comment]
Thanks, this one seems to have been already fixed on the unstable build.
