### ISSUE TITLE
Fix GeneralStore casing

### ISSUE THREAD

**Issue by Glinkis** [ryceg/Eigengrau-s-Essential-Establishment-Generator#195]
All of the GeneralStore names are currently *PascalCase*, while everything else is *camelCase*.
This is slightly confusing and should probably be corrected.

**Comment by Glinkis** [comment]
The file names are still *PascalCase*. To change file name casing in git, it might be necessary to first  add or remove a letter in the name, commit, and then fix the name. Just changing the casing doesn't always register properly.

**Comment by ryceg** [comment]
What is the recommended course of action for cases where there's a word preceding it? i.e. `setup.createGeneralStore()`; is the preferred casing as is, or is it `setup.creategeneralStore()` to preserve unification?

**Comment by Glinkis** [comment]
Definitely as-is. Words that would be written separately normally, should always be an identifiable part of the variable name. Thus a word such as `substring` can be written as in the same casing.

**Comment by ryceg** [comment]
Fixed as of commit 98c0a32230836ea11f183d30e8b1da71a728bb69
