### ISSUE TITLE
Can't generate new micro-establishments

### ISSUE THREAD

**Issue by WishingOnAWendy** [ryceg/Eigengrau-s-Essential-Establishment-Generator#196]
**Describe the bug**
The Create New Building function isn't working for bakery, florist, tailor, butcher, or cobbler, it's throwing Error: `<<run>>: bad evaluation: Cannot read property 'key' of undefined.` and the console is throwing `A building was not passed!` and is not making a new building

**To Reproduce**
Just try to create a new building for any of the above listed

**Expected behavior**
Creates a new building for the selected establishment

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.80
--

**Comment by ever-3W** [comment]
https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/pull/199
