### ISSUE TITLE
Town Building Material

### ISSUE THREAD

**Issue by WishingOnAWendy** [ryceg/Eigengrau-s-Essential-Establishment-Generator#205]
**Is your feature request related to a problem? Please describe.**
Currently buildings just randomly select materials for each building. This leads to there being a lot of different building materials in different towns even on the same street from each other.

**Describe the solution you'd like**
Towns should generate a main building material that will skew the rolls of building materials heavily towards that main material.
IE If the main building material for the town is terra cotta then most buildings should be terra cotta and buildings made of other materials should be quite rare.
This could also tie in to roofs, although I think having different roof types is not as jarring.

**Comment by urielfcampos** [comment]
Can i give this a try ?

**Comment by WishingOnAWendy** [comment]
Yeah give it a whirl!
