### ISSUE TITLE
Dock Activity

### ISSUE THREAD

**Issue by WishingOnAWendy** [ryceg/Eigengrau-s-Essential-Establishment-Generator#208]
**Describe the bug**
Sometimes instead of printing the final sentence in the dock paragraph the generator simply outputs $docks.activity

**To Reproduce**
Just keep going to docks until one prints out $docks.activity instead of the proper text

**Expected behavior**
A descriptor from the docks.activity array should be pulled based on the rolls

**Screenshots**
https://i.imgur.com/E45QUNK.png

**Comment by WishingOnAWendy** [comment]
This is still occurring after the fix

**Comment by ryceg** [comment]
1c5a5c5 hopefully has fixed this.
