### ISSUE TITLE
Smithy Guard Chat

### ISSUE THREAD

**Issue by WishingOnAWendy** [ryceg/Eigengrau-s-Essential-Establishment-Generator#212]
**Describe the bug**
Sometimes when you talk with the blacksmith part of the conversation outputs as town.guard.captain.name.

**To Reproduce**
Talk to blacksmiths until this comes up

**Expected behavior**
Should print the name of the captain of the guard

**Screenshots**
https://i.imgur.com/s1nsbJF.png

**Comment by ryceg** [comment]
Fixed as at 5e8cb5e2d7fad6880486287ebc8a5f62932bdacd. Thanks!
