### ISSUE TITLE
Compile local version page doesn't exist in the wiki

### ISSUE THREAD

**Issue by urielfcampos** [ryceg/Eigengrau-s-Essential-Establishment-Generator#219]
**Describe the bug**
I was checking the wiki and noticed the page that talks about compiling the local version of the
project doesn't exist and just leads back to the home page.

**To Reproduce**
the page doesn't exist : https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/Compiling-the-Generator

**Expected behavior**
I believe this page should be written and include detailed instructions on how to compile and run a local version, even though it exists on the README. 
Also it would help to include the package versions that were used to build the project

**Comment by WishingOnAWendy** [comment]
I've just put one up, let me know if you would like to expand it and how

**Comment by urielfcampos** [comment]
Well, I tried to follow steps and it kinda of worked, but i needed to look around a bit first. 

My suggestion the for the installation part would be something more like this, what do you think ?

## Installation:
1. Clone the repository from github
2. Go into the directory and run ```$ npm install``` or ```$ yarn install``` to install all the dependencies required by the project
3. run the following command ```$ npm run install-compiler``` to download Tweego and the necessary files for it to work
   1.  Go inside the .twine folder
   2.   run the following command to enable the proper permission for tweego : ```$ chmod +x tweego```
4. Now you can run ```$ npm start``` to watch for file changes or ```$ npm run build``` to build the files once 
- The entire thing will output to the ```/gh-pages folder``` as the ```index.html``` file if you use the ```npm run build``` command 
- with ```npm start``` you can just reload the page after saving changes to the project


 
Now, i managed to build the project but i wonder if there is something else to install or configure ? 
Or maybe the master branch is a bit behind ?
When i open the index.html the following error pop up:
```
Apologies! An error has occurred. You may be able to continue, but some parts may not work properly.

Error [StoryInit]: <<set>>: bad evaluation: baseObj is undefined.
```
and the Main page looks like this: 
![Screenshot_20190626_172159](https://user-images.githubusercontent.com/31864637/60212460-b04d7400-9837-11e9-91c3-732a30bfcfe0.png)

**Comment by WishingOnAWendy** [comment]
You may have to refresh your browser/hit the restart buttons a few times, there's a bug in the current build that does that

**Comment by urielfcampos** [comment]
Yeah, that worked haha.
Would be nice to add a FAQ to the wiki with this info maybe ? To help new contributors.

**Comment by ryceg** [comment]
Added this as of 6d73ab6. Anything else that's needed? Otherwise, I'll close the issue.

**Comment by urielfcampos** [comment]
I believe that's all, you can close it.
