### ISSUE TITLE
Refactor location vegetation to an integer, rather than an array.

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#221]
Currently, vegetation and plants are array based; 

`setup.townData.terrain[town.terrain].location[town.location].vegetation` is: `['sparse', 'lush', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick']`, and `setup.townData.terrain[town.terrain].location[town.location].plants` is: `['shrubs', 'bush', 'windswept trees', 'windswept trees', 'windswept trees']`. 

This is obviously a huge waste of LoC, and can be refactored quite easily, and include more detail.

**Comment by lexcorp16** [comment]
Hi, @ryceg can you point me in the right direction as to what needs to be done? thanks.
