### ISSUE TITLE
Bad Evaluation Errors

### ISSUE THREAD

**Issue by trashxking** [ryceg/Eigengrau-s-Essential-Establishment-Generator#224]
**Describe the bug**
I have continuously been getting a "bad evaluation" error on NPC profiles whenever the page is refreshed while using the current master branch through localhost (as of writing on July 8th). If I click "Restart" to get a new town, the error is not there. However, if the page is ever reloaded the error reappears. As you can see, it also breaks NPC information regarding finances.
![image](https://user-images.githubusercontent.com/51835651/60818866-1a351a00-a164-11e9-9794-db706c350611.png)

`Error: <<set>>: bad evaluation: State.temporary.value is not a function`
`<<set _finances[_key] to _value($town, $currentNPC)>>`

`Error: <<set>>: bad evaluation: Cannot read property '0' of undefined`
`<<set _finances.tax to _finances.grossIncome - _finances.netIncome, _finances.totalLifestyleExpenses to _finances.lifestyleStandard[0] + _finances.lifestyleExpenses>>`

**To Reproduce**
1. Create a new town.*
2. Visit an NPC profile.
3. Refresh the page.
*The error also occurs if you save a town and then load it again, even if the browser page is not refreshed.

**Expected behavior**
I expected that NPC profiles would be preserved on refresh/reload.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 75.0.3770.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A (haven't tested)

**Comment by ryceg** [comment]
Thanks for this. Unfortunately, this is an issue with the way that Twine handles temporary variables, which are used to store the data for NPC finances. Twine in general just doesn't really like reloading, and there are no use cases where it is currently beneficial to refresh the webpage. We are currently in the middle of shifting to a React based architecture, which should sidestep the issue, so this will be marked as 'wont fix'.

**Comment by trashxking** [comment]
@ryceg That's fair, especially since you mention attempting to move away from Twine. However, I did mention this as well:
>*The error also occurs if you save a town and then load it again, **even if the browser page is not refreshed.** 

Would the shift to React also fix this? And even so, is there any kind of temporary solution that could be implemented in the mean time to address this specifically?  I really enjoy using the generator, so it's a huge bummer that I can't save and then reload any cities that are generated at the moment.

Of course, I understand if that's not currently feasible, I just thought I'd ask!

**Comment by kentaromiura** [comment]
> We are currently in the middle of shifting to a React based architecture, which should sidestep the issue, so this will be marked as 'wont fix'.

I was going to look into https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/issues/75, but this comment makes me wonder if the main branch now is the https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/commits/engine-migration-only-twee or if you have a more up to date local branch that's not published on github.

**Comment by Glinkis** [comment]
@kentaromiura
That's the newest version of the react migration, but I haven't been able to work on it in for a while now.
