### ISSUE TITLE
Pop up weirdness 

### ISSUE THREAD

**Issue by jackiscool231** [ryceg/Eigengrau-s-Essential-Establishment-Generator#227]
**Describe the bug**
Most of the time but not all of the time the pop up that give a description of the building some times looks like only a circle shows 

**To Reproduce**
Town Settings:
Settings of page (Tavern, Blacksmith, etc.)

**Expected behavior**
I assume that the intention for this is to have it be readable 

**Screenshots**
![73F7C674-60E2-457D-AFF2-CFA9CDA1160B](https://user-images.githubusercontent.com/52936488/61248539-e2f0db00-a718-11e9-992f-cc801a8c0104.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPad ?
 - OS: iOS 12.3.1
 - Browser Chrome
 - Version 2.2

**Additional context**
It happens most of the time

**Comment by ryceg** [comment]
Thanks for this, I don't own an iPad and will investigate why this is happening.
