### ISSUE TITLE
Two Misc Bugs

### ISSUE THREAD

**Issue by ZiluckMichael** [ryceg/Eigengrau-s-Essential-Establishment-Generator#23]
**Describe the bug**

- When you open the "Businesses" section, change the population, and try to open it again, the list will be blank or only have one entry. If you set it back to the original population, it will still be empty.
- For the ring generator, there was an option that said "gives the wearer the ability to control the weather, but the side effect was that "its powers are sometimes accompanied by a blizzard." This ability and side effect contradict each other. Not sure if this is intended.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 67.0.3396.87

**Comment by ryceg** [comment]
The businesses bug has been fixed, and the next update will fix it. 

As for the ring generator: I could create some exclusion code, but it's an incredibly unlikely scenario; there's a 1/16 chance to have the control power, 1/6 chance for it to be controlling the weather, and a 1/5 chance for it to be accompanied by environmental effects. I'm lazy, so I reckon it's gonna get labeled as a 'feature'! Besides, DMs are clever; sure, you might be able to control the weather, but it'll be replaced with the occasional blizzard!

**Comment by ZiluckMichael** [comment]
The business bug: sweet! Thanks :)

The ring generator: I actually thought it would make for a really funny magic item; it really would surprise the players. Just thought I'd mention it in case there were potentially other cases that could come up.
