### ISSUE TITLE
Button to request a new name for the village

### ISSUE THREAD

**Issue by craftecode** [ryceg/Eigengrau-s-Essential-Establishment-Generator#230]
**Is your feature request related to a problem? Please describe.**
Sometimes I like the scenario generated but would like different town for the name.

**Describe the solution you'd like**
A button to change it to randomise the village name to a new one. The button could possibly be the text of the name.

Thank you for making Eigengrau's generator!

**Comment by ryceg** [comment]
This is already a feature. If you go to "Description of `TownName`", and then "Edit `TownName`", there is a hyperlink next to `TownName` that says 'reroll'; hitting that will generate a new town name
