### ISSUE TITLE
Editable text & Sharing

### ISSUE THREAD

**Issue by craftecode** [ryceg/Eigengrau-s-Essential-Establishment-Generator#231]
It seems like it could be great if I could 
 - edit the generated text to customise it 
 - and add links to battlemaps and reference pictures 
 - and if there was a link to reddit or another forum where we could share and talk about our favourite villages and how we used them!

Seeing how people edit the generated text might give some inspiration for changing the generator.

**Comment by ryceg** [comment]
Eigengrau's currently supports a *limited* amount of customisable text- NPCs and some aspects of buildings can be edited, but this is hopefully something that will be implemented in the React rebuild. 

We have a Discord (https://discord.gg/eugm5q2) and Subreddit (www.reddit.com/r/EigengrausGenerator) which are currently the main hubs for discussion. Please feel free to drop in and join the conversation!
