### ISSUE TITLE
Word positioning - "She all non-proper nouns end with"

### ISSUE THREAD

**Issue by craftecode** [ryceg/Eigengrau-s-Essential-Establishment-Generator#232]
**Describe the bug**
"She all non-proper nouns end with" should be either "She ends all non-proper nouns with"

**To Reproduce**
Town Settings: The Town Square > a person who was there

**Screenshots**
![image](https://user-images.githubusercontent.com/41639393/64944268-a9eaf900-d876-11e9-89eb-0a7ca923f669.png)

**Desktop (please complete the following information):**
 - Chrome on Windows 10

**Comment by ryceg** [comment]
Thanks for this, will edit it to sound more natural.

**Comment by ryceg** [comment]
Fixed in b2e3dac3271e75e8f7fb27fed44fb4a2e1d585a5
