### ISSUE TITLE
Blacksmith semicolon misuse and a word double up

### ISSUE THREAD

**Issue by craftecode** [ryceg/Eigengrau-s-Essential-Establishment-Generator#234]
**Describe the bug**
Use of a semicolon is wrong I think and sweep is said twice. 
“You can see that activity in Kayla and Uncle is very busy; the smithy is very tidy, with a swept floor and tools stored neatly on the bench in a row. The forge has been recently swept, and there's a surprising lack of grime.”

**To Reproduce**
Town Settings: blacksmith

**Expected**
The semicolon - After “very busy;” there should be some kind of way in which the forge is busy such as several people working or a few patrons inspecting items. Otherwise the semicolon could be removed and it could say “is very busy but also very tidy”.

The swept duplicate - “With a swept floor and tools stored neatly on the bench in a row. The forge has been cleaned recently...”

 - iPad chrome

**Comment by ryceg** [comment]
Fixed in #7e9f26a
