### ISSUE TITLE
‘Becoming a hunter’ character detail doesn’t seem to fit with a child of the nobility wealth class

### ISSUE THREAD

**Issue by craftecode** [ryceg/Eigengrau-s-Essential-Establishment-Generator#235]
![6487572A-5527-4C12-A6C5-37AA9AC75495](https://user-images.githubusercontent.com/41639393/65383847-9bdc2300-dd23-11e9-9024-60fc97661d13.png)

**Describe the bug**
‘Becoming a hunter’ character detail doesn’t seem to fit with a child of the nobility wealth class.

**Comment by WishingOnAWendy** [comment]
You are correct, this is something that needs to be addressed with a full rework of how children are created. Thank you for pointing it out!

**Comment by ryceg** [comment]
Closing as #263 more accurately describes the isssue.
