### ISSUE TITLE
defineRollDataGetter.js is not fetching the last element of an array as a fallback

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#245]
**Describe the bug**

**To Reproduce**
Pass it a tavern(or any building) with a negative wealth value, and it will spit out an error.

**Expected behavior**
It should grab the last entry in an array as a fallback if the `.find` returns an `undefined` result.

**Comment by Fleker** [comment]
Is this being used anywhere that could be used to debug what's going on?

**Comment by Glinkis** [comment]
It's defined [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/blob/e958cc0bbeb06f81c36c741f1fa2a6b707700c4d/lib/src/defineRollDataGetter.ts#L34), and you should be able to find usages my checking the references, or searching.

A proper unit test for this function would be immensely useful.

**Comment by Fleker** [comment]
I setup a few unit tests. It does seem like the behavior is correct, as the unit tests pass (based on my understanding of the code).
