### ISSUE TITLE
Change factions and town name in descriptions when town name is changed

### ISSUE THREAD

**Issue by Zalatos** [ryceg/Eigengrau-s-Essential-Establishment-Generator#259]
**Describe the bug**
i went into edit village , changed the name from Icehenge to Ivalice.
but several of the factions still had Icehenge in the their  title as well as writeups described certain npcs as leaders of icehenge

**To Reproduce**
Go into edit village , changed the name from whatever it is to another.
check description of building pr society for occurrences of the old village name

**Additional context**
there used to be a feature where u could edit the writeup in npcs and such. i may just be missing it. would be useful to be able to sort out these issues as a user

**Comment by ryceg** [comment]
Duplicate of #274 (I know this one came first I'm just very stupid and already made reference to #274 in other issues so this one gets the axe sorryyyyyy)
