### ISSUE TITLE
toUpperFirst is not defined on NPC Profile page & other pages

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#267]
**Describe the bug**
toUpperFirst is not defined on NPC Profile page- not always, but sometimes.

**To Reproduce**
Town Hash (the bit that comes after eigengrausgenerator.com- typically in the format of #adjectiveadjectiveanimal): #curvybountifullovebird
Page to navigate to, buttons to press, etc: Town page > Corrin Tenpenny

**Comment by Tazshelby2016** [comment]
It occurs on every NPC page I saw for me. I'm on chrome on Windows 10.

**Comment by ryceg** [comment]
Partially addressed, but leaving open since I think that there are still edge cases.
