### ISSUE TITLE
Tavern material is [object Object]

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#270]
![image](https://user-images.githubusercontent.com/36913739/84009298-690fb300-a9b6-11ea-8ac2-737b536a1c70.png)

**Comment by Glinkis** [comment]
This happens when trying to print an object as a string.
For example `console.log(String({}))`.

**Comment by ryceg** [comment]
Yep, pretty sure I know exactly where it's gone wrong- I can fix this
tomorrow morning.

**Comment by Glinkis** [comment]
Narrator:

> It was not fixed tomorrow morning

**Comment by ryceg** [comment]
Apologies in advance for breaking the typescript!
