### ISSUE TITLE
Remove Building Button

### ISSUE THREAD

**Issue by sanfordjd** [ryceg/Eigengrau-s-Essential-Establishment-Generator#286]
**Describe the solution you'd like**
It would be handy if buildings could be removed from the description

**Describe alternatives you've considered**
Ignore Buildings ... but if you're saving and coming back later it can be difficult to remember previous choices.

This is AWESOME 
And I'll 100% be using it in my next game I DM.

**Comment by ryceg** [comment]
Fixed in 813cbdb
