### ISSUE TITLE
Flavor text generation error: reads "<>" instead of generating text

### ISSUE THREAD

**Issue by quona** [ryceg/Eigengrau-s-Essential-Establishment-Generator#29]
**Describe the bug**
On mouseover of a generated tavern name (it generated "The Stumbling Rat and the Labyrinth," if that matters), the flavor text reads: "A small tavern that's absolutely putrid, and is know for its <> atmosphere."

**To Reproduce**
Town Settings:
Main town page, under Description of $Town (in this case, "Heartvorn"). Full text on page reads: "On Common Square is the tavern The Stumbling Rat and the Labyrinth"

**Expected behavior**
Expected flavor text of the atmosphere to generate, instead got "<>"

**Screenshots**
![bugreport8118](https://user-images.githubusercontent.com/42000483/43524742-014ad69a-956e-11e8-8f1a-89c33dc96dd4.png)

**Desktop (please complete the following information):**
 - OS: Win 7 Professional
 - Browser: Chrome
 - Version: 67.0.3396.99 (Official Build) (64-bit)

**Additional context**

**Comment by ryceg** [comment]
Thanks for this bug report, has been fixed in the next update.
