### ISSUE TITLE
Editing towns sometimes causes errors in Firefox

### ISSUE THREAD

**Issue by Holymittens** [ryceg/Eigengrau-s-Essential-Establishment-Generator#292]
**Describe the bug**
Generated a new town, went to the town's description, and clicked "Edit". It generates the following error:
Apologies! An error has occurred. You may be able to continue, but some parts may not work properly.

Error: setup.articles.output(...) is undefined.

Stack Trace:
setup.profileTooltip/<@https://eigengrausgenerator.com/#cornyshinynudibranch line 56169 > eval:38167:63
e@https://eigengrausgenerator.com/#cornyshinynudibranch:59:29453
l/</t<@https://eigengrausgenerator.com/#cornyshinynudibranch:59:29755

**To Reproduce**
Town hash: /#forsakensandysenegalpython
Click on "Description of Ratki" then "Edit Ratki". The error appears.

**Additional context**

**Comment by gendernihilist** [comment]
Same here: 

Apologies! An error has occurred. You may be able to continue, but some parts may not work properly.

Error: setup.articles.output(...) is undefined.

Stack Trace:
setup.profileTooltip/<@https://eigengrausgenerator.com/#waterloggedlankyangelfish line 56169 > eval:38167:63
e@https://eigengrausgenerator.com/#waterloggedlankyangelfish:59:29453
l/</t<@https://eigengrausgenerator.com/#waterloggedlankyangelfish:59:29755

**Comment by ryceg** [comment]
Duplicate of #267
