### ISSUE TITLE
Error when clicking the Toolbox button

### ISSUE THREAD

**Issue by SleepyWisp** [ryceg/Eigengrau-s-Essential-Establishment-Generator#293]
Every time I press the Toolbox button on the UI bar, the banner (on the main portion of the site, not the UI bar) is replaced with the text "Meet one of the patrons!", and underneath that it displays the following error:

> **Error: <<if>>: bad conditional expression in <<if>> clause: State.variables.building is undefined**
> <<if def $building.drinker>>\<div class="descriptive">
>   \<h3>$building.drinker.name</h3>
>   \ <<print setup.articles.output($building.drinker.descriptor)>> is currently <<print $building.drinker.idle.random()>> in the corner. You strike up conversation with $building.drinker.himher, and the $building.drinker.descriptor introduces $building.drinker.himherself as <<profile $building.drinker>>, a <<print $building.drinker.dndClass || $building.drinker.profession>> who is <<print $building.drinker.adventure || "looking for a drinking buddy">>. You talk about your backgrounds, and $building.drinker.heshe says "I was <<print setup.articles.output($building.drinker.background)>> before I was <<print setup.articles.output($building.drinker.dndClass)>>. $building.drinker.backgroundOrigin $building.drinker.bond" <<print $building.drinker.heshe.toUpperFirst()>> looks at you with $building.drinker.hisher $building.drinker.eyes eyes for a moment, and says "Actually, you might be interested; <<print ["<<print setup.plothook.people.random()>>", "<<print setup.plothook.rumour.random()>>"].random()>>"</div><<else>><span id="NPC"></span><</if>>

I'm using Firefox (version 76.0.1), and the town hash is #simplisticbowedladybird (but the error seems to occur on every town I generate).

**Comment by ryceg** [comment]
Fixed in 813cbdb
