### ISSUE TITLE
lib.professions has broken some things.

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#302]
**Describe the bug**
![image](https://user-images.githubusercontent.com/36913739/85944062-7d245000-b977-11ea-97f5-90071fa7bdc4.png)

**To Reproduce**
Town Hash (the bit that comes after eigengrausgenerator.com- typically in the format of #adjectiveadjectiveanimal):
Page to navigate to, buttons to press, etc: town description > professions

**Additional context**
Unclear whether it's just that instance; could be more, somewhere.

**Comment by Glinkis** [comment]
Fixed via e8f42be58722e2ff86b2e8f7d46494d966129db6
