### ISSUE TITLE
page not loading anything 

### ISSUE THREAD

**Issue by mickeymousez321** [ryceg/Eigengrau-s-Essential-Establishment-Generator#304]
When I open the page it instantly pops up an error message and then nothing on the page loads. 
![ss twn gen](https://user-images.githubusercontent.com/67872888/86538766-07177000-bec6-11ea-9501-cb4fc1124cd8.png)

**Comment by ryceg** [comment]
Please provide the seed and steps to reproduce this issue.

**Comment by mickeymousez321** [comment]
I dont have a seed im not sure what that is.
The steps to reproduce
1. Type in website address
2. Get error message
3. Page doesn't load anything
That picture is what I see as soon as I go to the website.

**Comment by ryceg** [comment]
The seed is the part that comes after https://eigengrausgenerator.com/**#adjectiveadjectiveanimal**

**Comment by ryceg** [comment]
Closing due to lack of information. I will reopen if there is a seed provided.

**Comment by mickeymousez321** [comment]
There is nothing that comes after that part all I have is https://eigengrausgenerator.com/

**Comment by ryceg** [comment]
Please try the following link: https://eigengrausgenerator.com/#creativewindybaiji

You should have the town of Hutherhammer.

**Comment by mickeymousez321** [comment]
![error](https://user-images.githubusercontent.com/67872888/87112344-9069d200-c239-11ea-99b0-4e48d0b52310.png)
it did the same thing

**Comment by Glinkis** [comment]
What browser/version är you using?

**Comment by mickeymousez321** [comment]
I use Microsoft edge

**Comment by ryceg** [comment]
Can you please try using Google Chrome and confirm that the issue still
persists?

**Comment by Glinkis** [comment]
Which version of edge is that?

**Comment by mickeymousez321** [comment]
i think its version 42.17134.1098.0 im no really sure where to find that information

**Comment by mickeymousez321** [comment]
it actually did open on chrome
