### ISSUE TITLE
Alchemist buying interface setup.closestMatch error

### ISSUE THREAD

**Issue by lunamoon03** [ryceg/Eigengrau-s-Essential-Establishment-Generator#308]
**Describe the bug**

In the output for "Buy Something", there is a red box that reads "Error: <<print>>: bad evaluation: setup.closestMatch is not a function"
**To Reproduce (bugs MUST be replicable)**

Town Seed (click [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/FAQ#people-keep-talking-about-seeds-what-is-a-seed) for info): 
#fortunatepointedsable
Page to navigate to, buttons to press, etc:
Go to the Fluorescent Mortar and Pestle alchemists and press the Buy Something button
**Additional context**

**Comment by ryceg** [comment]
Thanks for this, @lunamoon03. It's hugely helpful, appreciate it.

**Comment by ryceg** [comment]
Fixed in next update
