### ISSUE TITLE
Refactor factionData.ts arrays into objects with probabilities.

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#311]
Several of the `factionData.ts` arrays have duplication intended to represent probability. This, however, is not very efficient, and obfuscates the nature of the code. 

The following are in need of refactoring: 
* leaderQualification
* alliesList
* rivalsList
* joiningRequirement
* joiningInitiation
* membersTrait
* motivation
* resources

Additionally, the arrays associated with name generation should be rehoused in an object containing them, named `names`. The offending are:
* main
* adjective
* group 
* unique

Refactoring the relevant code will be necessary, but should be a relatively simple swap to using `lib.weightRandom` (see `town.vegetation` for an example)

**Comment by alcar** [comment]
Hey, @ryceg! I'm not familiar with the codebase, but I'm happy to give this a try if that's okay!

**Comment by ryceg** [comment]
Absolutely! Should be relatively straightforward, if you're not already on the discord server then please feel free to join, that's where the discussion of development takes place :)

**Comment by alcar** [comment]
Thanks! I'll start working on it! :sparkles:
