### ISSUE TITLE
Error with Alchemist Shop Inventory Dialogue

### ISSUE THREAD

**Issue by NickAvallone** [ryceg/Eigengrau-s-Essential-Establishment-Generator#319]
**Describe the bug**

In an Alchemist shop, when you click "Buy Something" it throws an error in the dialogue panel.

Darrak Rumnaheim says "Sure, what are you after? **Error: <<print>>: bad evaluation: Cannot read property 'random' of undefined?** Or perhaps a potion? **Error: <<print>>: bad evaluation: setup.closestMatch is not a function"**

**To Reproduce (bugs MUST be replicable)**

Town Seed (click [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/FAQ#people-keep-talking-about-seeds-what-is-a-seed) for info): #femaledutifulstinkpot

Page to navigate to, buttons to press, etc:

**Additional context**

**Comment by ryceg** [comment]
Hi Nick, thanks for the issue- it really helps (nobody likes to go find the bugs in their own code, but _somebody_ has to). For future reports, please include the seed, which is the bit after the url (#femaledutifulstinkpot, for example).

**Comment by ryceg** [comment]
Fixed in the unreleased build :)
