### ISSUE TITLE
CSS for header needs tweaking

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#327]
![image](https://user-images.githubusercontent.com/36913739/94093781-62bc1e80-fe61-11ea-95d1-d88a26b9cac9.png)

In the current build, the white background does not extend all the way to the left, and is aligned with the passage content. Using a css of `left: 0;` unfortunately also puts the text to the left. The text should ideally be aligned (with a padding of maybe 3px), but the white and brown line should cover the entire top left. I'm a smoothbrain and can't figure it out. It's probably very simple.

**Comment by Fleker** [comment]
To achieve this I believe you may want to look at the [position: sticky](https://www.w3schools.com/howto/howto_css_sticky_element.asp) attribute. I'll try out a PR.

**Comment by Fleker** [comment]
While the header originally is set to a position of `fixed`, that is overridden by a position of `sticky`. So there should be some padding that keeps it aligned with the page content while allowing the outer element to fill the screen.

**Comment by Glinkis** [comment]
I think this is superceded by #339, you you guys like the change.
