### ISSUE TITLE
Faction Issue

### ISSUE THREAD

**Issue by Draygor** [ryceg/Eigengrau-s-Essential-Establishment-Generator#329]
Hi, I have only just discovered this generator, which is fantastic. I am not a coder or developer, but a very appreciative user.

The issue I am experiencing is that after creating a faction, very frequently if I click on the name to get more detail, I just get red error banners all through the text. 

The heading is $currentFaction.name.

In between every screen I am also getting a little drop down window with the error message - "Apologies an error has occurred".

Town Seed - #unwillingconcernedamberpenshell

Page to navigate to, buttons to press, etc:
The city of Baldur's Gate > Unterton > Editing Town > Baldur's Gate > The League of Unpaid Creators

![image](https://user-images.githubusercontent.com/71924948/94338102-a93b8580-ffe7-11ea-8bf8-0385d842ede7.png)

**Comment by ryceg** [comment]
Hi @Draygor, thanks for submitting this bug report. I am unable to replicate this issue, and suspect that you have omitted replication steps- Baldur's Gate is a copyrighted WotC term, and does not feature in the engine very deliberately.

**Comment by ryceg** [comment]
Closing due to inability to replicate issue.
