### ISSUE TITLE
Refactor createTownBiome & createTown into a single function

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#347]
When the `Show town biome prompt upon restart?` setting is set to `true`, the generator first spins up a "draft" town using `createTownBiome()`, which does not have all of the properties of the full town creation function. This is then passed to the `createTown()` function, which fills in the gaps. It's super ugly repeated code, and could be refactored rather more efficiently.

This would involve a Ctrl + F for `$tempTown`, which only appears in a couple passages.

**Comment by Glinkis** [comment]
Passing booleans to functions is generally a bad idea. It's usually better to extract the shared logic to separate smaller functions that do one thing each.

**Comment by ryceg** [comment]
TIL!

**Comment by Glinkis** [comment]
See:
https://martinfowler.com/bliki/FlagArgument.html
https://understandlegacycode.com/blog/what-is-wrong-with-boolean-parameters/
https://www.informit.com/articles/article.aspx?p=1392524
