### ISSUE TITLE
Add Foundry Export functionality

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#350]
There is an extensive [API](https://foundryvtt.com/api/) for Foundry, but a simple JSON copy + paste would also be sufficient, at least for the shortterm.

**Comment by SnortsAlot** [comment]
https://trello.com/invite/b/5neFnUv5/718e3751c9418c651807ceced750007f/systems

I'd suggest joining https://discord.gg/6nuYQghPge
To get help or answer questions on the API for such
