### ISSUE TITLE
Refactor goods objects into arrays

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#358]
`goodsAndServices.js` has a `goods` value for every entry, which should be refactored into an array. 

e.g.
```js
goods: {
        'short boots': {
          cost: 10,
          description: 'A pair of barely ankle height boots made of some kind of leather'
        },
```

should become

```js
goods: [
        {
          summary: 'short boots',
          cost: 10,
          description: 'A pair of barely ankle height boots made of some kind of leather'
        },
```

This would involve a minor refactoring of the `<<goods>>` widget located in `Widgets.twee`.

**Comment by alcar** [comment]
Hey, @ryceg! Can I work on this one?

**Comment by ryceg** [comment]
Please do @alcar!

**Comment by femakin** [comment]
can I still work on this?

**Comment by alcar** [comment]
Sorry @femakin, I'm already working on it :slightly_frowning_face:
