### ISSUE TITLE
Support for translation

### ISSUE THREAD

**Issue by Philippe-Arnaud** [ryceg/Eigengrau-s-Essential-Establishment-Generator#37]
**Is your feature request related to a problem? Please describe.**
The content is only provided in English.

**Describe the solution you'd like**
The project should support translation of the content, without having to fork and patch the content, solely relying on Git mechanics.

**Describe alternatives you've considered**
Relying on forks and hard-coded translation breaks the experience and is not providing a single-entry point to the project.

**Additional context**
Translation should ideally be supported through merge requests and separated language content files that would cover a translation.
This solution would also provide with an elegant theming solution that could address various environments and settings.

**Exemples**

* MedFan_EN.js: current content
* MedFan_FR.js: translation of current content in French
* Contemporary_EN: content reflecting a setting in the current time
* Cyberpunk_RU: content in Russian for a cyberpunk setting
* Coriolis_SE: swedish setting for a specific RPG (Coriolis)

**Comment by ryceg** [comment]
Hi Philippe, 

Thanks for raising this issue. Unfortunately I am a monoglot, and this is a small project that is maintained largely by myself, with a similarly small user base. Without somebody dedicated to translating quite literally almost all of the code, this matter is beyond the scope of the project.

**Comment by fdelia** [comment]
Sorry for commenting in a closed thread.

I'd support translation to German, meaning I would translate it. 

Only if the need for it arises.

**Comment by ryceg** [comment]
Very generous of you, fdelia, but the project is approaching a novel's worth of content that would need translation- far too much for one person!
