### ISSUE TITLE
Church Attendees do not load correctly

### ISSUE THREAD

**Issue by spwack** [ryceg/Eigengrau-s-Essential-Establishment-Generator#373]
**Describe the bug**

Eval errors displayed: Error: <<run>>: bad evaluation: npc.partnerGenderProbability is not a function, <<run setup.expandNPC($town, $npcs[$currentPassage.key])>> etc. whenever NPCs are clicked on in the "Church Attendees" list.

**To Reproduce (bugs MUST be replicable)**

Town Seed: noxioushotpinkantbear
The Cathedral of Understanding Lovers > Church Attendees > Relationships> Any NPC

Multiple errors displayed scattered about the page.

**Comment by ryceg** [comment]
Hi @spwack, thanks for this- I'm trying to replicate this but the only attendee to start is Gob Strongbones, and none of the npcs in his relationship tree seem to have the error you're describing.
