### ISSUE TITLE
Shop 'Buy Something' Button Error - Alchemist?

### ISSUE THREAD

**Issue by Ko-Zilek** [ryceg/Eigengrau-s-Essential-Establishment-Generator#374]
"Buy Something" button throws up an error, it does it every time.
https://eigengrausgenerator.com/#weightylastingindianringneckparakeet

Page to navigate to, buttons to press, etc:

Ain this case an alchemist I generated, I used this seed in an incognito tab see if it was a extension doing it; Had to gen a new alchemist, tried again, same deal.

![image](https://user-images.githubusercontent.com/24425229/96365896-aa4b7700-118f-11eb-8f66-30fda2739a1c.png)
![image](https://user-images.githubusercontent.com/24425229/96365907-c2bb9180-118f-11eb-8398-d93f7d06d780.png)
![image](https://user-images.githubusercontent.com/24425229/96365914-d49d3480-118f-11eb-99e5-83ec22daebec.png)
![image](https://user-images.githubusercontent.com/24425229/96365962-31005400-1190-11eb-8b37-e09dde4fdef4.png)

Tried a different store:
![image](https://user-images.githubusercontent.com/24425229/96366132-56da2880-1191-11eb-96f9-5fb09f90e112.png)

And it worked just fine:
![image](https://user-images.githubusercontent.com/24425229/96366141-6a858f00-1191-11eb-812b-5534512f0918.png)

Tried a general store and it worked just fine:
![image](https://user-images.githubusercontent.com/24425229/96366204-c3552780-1191-11eb-8fc4-11a11f995a9a.png)

Tried a different Alchemist and got the error:
![image](https://user-images.githubusercontent.com/24425229/96366231-f4cdf300-1191-11eb-8585-4dddbf31b0fa.png)

I'm guessing it has something to do with the alchemist.

I hope this sufficient in helping fix this error.

**Comment by ryceg** [comment]
Thanks for the detailed bug report! I have successfully found the bug, and will push it to live shortly.
