### ISSUE TITLE
Error Messages in Pop-Ups and Throughout Main Page

### ISSUE THREAD

**Issue by KainanSilverlight** [ryceg/Eigengrau-s-Essential-Establishment-Generator#375]
Upon loading the main page for the first time/after hitting “Restart”, to pop-up boxes with error messages appear:

“ Apologies! An error has occurred. You may be able to continue, but some parts may not work properly.
Error [tw-user-script-0]: Unexpected token '='. “
and
“ Error [StoryInit]: <<run>>: bad evaluation: setup.urlSeed is not a function. (In 'setup.urlSeed()', 'setup.urlSeed' is undefined). “
then, the main page itself is riddled with more error messages, throughout every section of the generator (including between instructive text).

I have attached a few relevant screenshots that will hopefully help.
![741B36AE-A08D-46FA-9193-DFFFC45F9CC3](https://user-images.githubusercontent.com/73063025/96366990-881b1000-1121-11eb-8e39-f30d69828902.png)
![1EECE9FD-C602-428A-A077-4CE4A506F2EA](https://user-images.githubusercontent.com/73063025/96366992-89e4d380-1121-11eb-963e-6b99ec585244.png)
![5CF1D2FE-E5A5-4953-A6A0-78320BA7A078](https://user-images.githubusercontent.com/73063025/96366993-8a7d6a00-1121-11eb-8bf5-590e21b9f55f.png)
![107289D1-258C-4A53-A844-0F7131A68095](https://user-images.githubusercontent.com/73063025/96367017-a7b23880-1121-11eb-93a6-3c1ce0164e21.png)
![18C685D1-0030-4E16-9C4F-11E64DFDF234](https://user-images.githubusercontent.com/73063025/96367020-aaad2900-1121-11eb-9578-408e7f1b6a60.png)
![D1E2AB39-785A-4F93-8FBE-82801EE96517](https://user-images.githubusercontent.com/73063025/96367021-ab45bf80-1121-11eb-99bd-6d1e57981dd0.png)

**Comment by ryceg** [comment]
Hi, thanks for submitting this. In order to us to be able to help, please provide the town Seed (click [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/FAQ#people-keep-talking-about-seeds-what-is-a-seed) for info).

**Comment by KainanSilverlight** [comment]
Unfortunately, it doesn’t actually seem to get far enough to generate a seed to even provide you. There is no “ bit after https://eigengrausgenerator.com/, usually in the form of #adjectiveadjectiveanimal “. The address in the web bar is just the base address. Pressing any buttons on the page just cause more error messages to appear (or nothing happens at all). Like so (areas circled in yellow were clicked on/interacted with, leading to next photo in sequence: 
![3EBF9BF7-C274-41B3-8230-EC635E333534](https://user-images.githubusercontent.com/73063025/96367821-7425dd00-1126-11eb-8341-8826a04481ff.jpeg)
![3A130370-55F2-4AED-BE99-2E3AC9378D8A](https://user-images.githubusercontent.com/73063025/96367826-76883700-1126-11eb-9907-241895ffda9c.jpeg)
![61A7FEFC-2647-429B-B751-FE2ABD9EF32A](https://user-images.githubusercontent.com/73063025/96367827-7720cd80-1126-11eb-822b-17c8d6353efb.jpeg)
![2C923176-1A12-45D3-B81F-320BCD3BAB9D](https://user-images.githubusercontent.com/73063025/96367828-77b96400-1126-11eb-916e-394c8107848a.jpeg)
![704AD5CC-C79B-471E-87D5-2D9B6428C3AF](https://user-images.githubusercontent.com/73063025/96367830-77b96400-1126-11eb-8d87-62e1ac661537.png)

**Comment by Tazshelby2016** [comment]
I got the same error. This breaks already generated content, and occured for me after saving 10-30 NPCs. What breaks seems to vary.

**Comment by ryceg** [comment]
@Tazshelby2016 I'm afraid you'll need to provide a little more context; it appears @KainanSilverlight's error occurs before _any_ activity is taken. Please follow the standard bug report format so we can try and replicate the issue that you are having to determine whether it is in fact related. 

@KainanSilverlight could you please test [this link](https://eigengrausgenerator.com/#triangularrealdowitcher)? If that doesn't work, if you could provide the make and model of your hardware, as well as the browser version and any ad block software that you have installed, that would be very helpful.

**Comment by KainanSilverlight** [comment]
Sorry, that link you provided appears to show the same error codes. 
I’m currently using an iPhone XR, model NT352LL/A, software version 13.6.
Browser is Safari, though unfortunately I can’t seem to find the version number in my settings.

**Comment by ryceg** [comment]
Could you try using Chrome or Firefox, to see if that works? That will help us narrow down whether it's an iPhone, or Safari issue.

**Comment by KainanSilverlight** [comment]
I’ve downloaded the latest version of Chrome from Apple’s App Store, and I’m getting the same issues immediately upon loading. I have an older iPad model (not sure which one, not with me at the moment) which seems to have the same problems as well. Unfortunately no laptop/desktop to try with.

**Comment by GraydonScates** [comment]
I am on a Macbook in Chrome Version 83.0.4103.61 and receiving the same error. I had never been to the site before, followed a link to the base domain (no seed) and see the same errors. Attaching the first errors in the console in case that helps. It looks like maybe a broken assignment somewhere.

![Screen Shot 2020-10-19 at 8 47 06 AM](https://user-images.githubusercontent.com/39167207/96452936-c8dd5c80-11e7-11eb-833c-0434db4a1a16.png)
