### ISSUE TITLE
$lord.lastName variable shows when talking with store owner

### ISSUE THREAD

**Issue by wesmangum** [ryceg/Eigengrau-s-Essential-Establishment-Generator#38]
**Describe the bug**
See title. Full dialog is:

"Jaxon looks content, and while you chat, he moves around the shop, preparing a new project for work. Jaxon loves working in The Silvered Bronze, and says that the patrons of The Silvered Bronze are fairly generous with their coin. You ask Jaxon about his current project, and he says "I'm working on a iron crossbow for Lord $lord.lastName's son.""

**To Reproduce**
Town Settings:
Desert,
Blacksmith store, default settings

**Expected behavior**
Shopkeeper's dialogue should say the lord's last name.

**Screenshots**
![image 2019-01-17 at 9 56 25 am](https://user-images.githubusercontent.com/5713417/51330966-46d26980-1a3e-11e9-9236-f580e607af7e.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by ryceg** [comment]
Thanks, have fixed this.
