### ISSUE TITLE
Cannot read property on Marriage Formations

### ISSUE THREAD

**Issue by kdeigs** [ryceg/Eigengrau-s-Essential-Establishment-Generator#390]
Error: <<run>>: bad evaluation: Cannot read property '40a4b7a0-99d6-4f62-99c2-ff3ce1c25a7e' of undefined

With 40a4b.... being a different error each time. The NPC page on which this is created always has only one relationship and their wife/husband is not on the list itself. Early life also becomes broken with birthplace being replaced with $currentNPC.birthplace etc. This is exactly mirrored in their partner's page as well. Happens somewhat randomly, but the one throughline I've found is that it happens with marriages after forming a relationship and attempting to expand an NPC (just through looking at the console).

**Comment by ryceg** [comment]
Please follow the bug template format- we cannot debug if we cannot replicate the error!
