### ISSUE TITLE
Faction resources only select one item type

### ISSUE THREAD

**Issue by nicolinilr** [ryceg/Eigengrau-s-Essential-Establishment-Generator#394]
![Screenshot from 2020-11-11 12-40-56](https://user-images.githubusercontent.com/73041516/98863493-509c3c80-241d-11eb-8692-cdaa335c7a86.png)
**Describe the bug**

When using the version of the generator currently live in browser (Chrome), navigating to the town description, and then the governing faction, and looking at the resources lists the same resource over and over. The resource can be different with new town generations, but is always the same in each town.

**To Reproduce (bugs MUST be replicable)**

Town Seed: #immaculatecomplicatedgecko #shabbygreatkomododragon #determinedfataldugong

From start page, click on Description of &lt;Town Name&gt;, then under "Law and Order" click the linked name of the policing faction, and the error is found on that pages Resources section.

**Additional context**

**Comment by ryceg** [comment]
Fixed in 4c7ea3d
