### ISSUE TITLE
Add Export to PDF Functionality

### ISSUE THREAD

**Issue by jmdrake4848** [ryceg/Eigengrau-s-Essential-Establishment-Generator#397]
**Is your feature request related to a problem? Please describe.**
I would love it if this could be exported to a pdf cleanly. When you print to pdf you get the UI bar and the coloring does not extend to a second page all the way.

[Link to example](https://drive.google.com/file/d/1LruyeYTmaUvyPQn732dOc1KtM6zDmYn_/view?usp=sharing)

**Describe the solution you'd like**
A selection to export to pdf with no ui bar and correct coloring.

**Additional context**
I would love to be able to take this to a gaming table as a print. Even if its a png/jpeg that would be awesome. This is an awesome generator!

**Comment by ryceg** [comment]
This is something that we really want to implement, but need to implement _right._ Unfortunately it looks, at least at the moment, like there are not many options that fulfil all of the following criteria;

* Independent of client viewport size (i.e. if you export on phone, it won't export a janky phone size pdf)
* Maintains OCR and text highlightability
* Can be run locally (with no calls to outside services) / is relatively straight forward to set up

Our current backup plan is to develop ways to make exporting to services such as GMBinder a smoother experience (#85); their business is formatting, so it makes sense to not try and reinvent the wheel when there's a great compromise in front of us.
