### ISSUE TITLE
Toolbox page's "Describe the weather" dropdowns and variables not working

### ISSUE THREAD

**Issue by wesmangum** [ryceg/Eigengrau-s-Essential-Establishment-Generator#40]
**Describe the bug**
The Toolbox page's "Describe the weather" section has two empty dropdowns, and when generating a description, the variable `$weather.precipitationReadout` shows.

**To Reproduce**
Go to Toolbox "Describe the weather"
Select a season from the dropdown
Generate a description

**Expected behavior**
The other two dropdowns should be populated and the generated text should correctly render variables.

**Screenshots**
![image 2019-01-17 at 10 21 36 am](https://user-images.githubusercontent.com/5713417/51332646-b72eba00-1a41-11e9-8bea-9d18600eb867.png)

**Desktop (please complete the following information):**
 - OS: macOs Mojave
 - Browser: Chrome
 - Version: Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by ryceg** [comment]
Thanks. This feature's been deprecated, so I'll close the issue
