### ISSUE TITLE
Local build isn't accessing images

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#400]
**Describe the bug**
The local build (run using `yarn start`) outputs to `/gh-pages/index.html`, while the live build (https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/tree/gh-pages) outputs to `/index.html`, resulting in the local build being unable to access the images.

![image](https://user-images.githubusercontent.com/36913739/99138730-da027780-2686-11eb-87fd-438b371f1145.png)

![image](https://user-images.githubusercontent.com/36913739/99138732-e2f34900-2686-11eb-8327-512d0dd9a514.png)

It's a CSS issue more than anything else.

**Comment by kevoneil** [comment]
@ryceg Hello!

We could just use a webpack plugin to copy these image files over to /gh-pages for local development. That would be one easy solution.

**Comment by ryceg** [comment]
That sounds great!
