### ISSUE TITLE
Errors and boxes filled with variables

### ISSUE THREAD

**Issue by Puddinglord** [ryceg/Eigengrau-s-Essential-Establishment-Generator#408]
Went to go look at an NPC and tried to get his early life. And got the following:

![image](https://user-images.githubusercontent.com/4474799/100472803-f51faf00-30aa-11eb-8949-0a113f565dcf.png)

My seed is: #fantasticentirehoverfly

**Comment by ryceg** [comment]
Thanks, this is fixed in the next update.
