### ISSUE TITLE
Tavern room pricing throwing error

### ISSUE THREAD

**Issue by jenthura** [ryceg/Eigengrau-s-Essential-Establishment-Generator#410]
**Describe the bug**

When generating a new tavern, saw [this error](https://i.imgur.com/GZf3mSJ.png).

**To Reproduce (bugs MUST be replicable)**

Town Seed: https://eigengrausgenerator.com/#deficientremorsefulvampirebat
I customized a lot of the town though, increasing several sliders to their maximums.
From the main page create a new tavern and check room prices.

**Comment by ryceg** [comment]
Thanks- This issue is already fixed and will be pushed to live in the next update.
