### ISSUE TITLE
Gender Miss-match in the Brothel Generator

### ISSUE THREAD

**Issue by theDinkus** [ryceg/Eigengrau-s-Essential-Establishment-Generator#420]
**Describe the bug**
Received this mismatched generation
"Apparently, it specializes in being an all male brothel." and "Rumours abound in whorehouses, and Over the River is no different; apparently, one of the harlots is actually a princess."

**To Reproduce (bugs MUST be replicable)**
Town Seed #draftymutedstagimpracticalnewstoat
Generated Additional Brothel
**Additional context**
Full Generation:
Over the River
As you make your way along Lords Drive two bearded men approach the largest member of your group and offer to sponsor him in a local pit-fighting tournament
You make your way down Lords Drive, and enter Over the River a rock building with a patchy straw roof. Inside, the cavernous rock building is very messy. You notice the sound of wood banging against wood echoing out from somewhere nearby.
When people talk about Over the River, they say the usual stuff; a new girl is making a stir. Apparently, it specialises in being an all male brothel.
Rumours abound in whorehouses, and Over the River is no different; apparently, one of the harlots is actually a princess.

Brothel Mistress

The Mistress is nowhere to be seen at first, but then emerges from a back room covered by thick curtains, she appears to be a sultry seductress. As soon as you enter the half-elf welcomes you warmly, and strides over to where you are. She introduces herself as Scarletta Sangster, the Mistress of Over the River, and asks what she can do for you.

Meet one of the harlots

Customers

**Comment by ryceg** [comment]
Thanks, I've amended the string to make it a little less weird.
