### ISSUE TITLE
Tavern Errors

### ISSUE THREAD

**Issue by sundararajan-s** [ryceg/Eigengrau-s-Essential-Establishment-Generator#425]
**Describe the bug**

While generating a tavern, the following appears:
`Error: <<print>>: bad evaluation: cleanliness.find is not a function`
`Error: cannot execute widget <<money>>: unable to parse macro argument "setup.getTavernLodging($building)": wealth.find is not a function`

**To Reproduce (bugs MUST be replicable)**

Any tavern seems to cause this.

**Comment by ryceg** [comment]
Thanks for this- this is a duplicate of #410 and has been fixed in the dev build.
