### ISSUE TITLE
Generate some raiders

### ISSUE THREAD

**Issue by drouu** [ryceg/Eigengrau-s-Essential-Establishment-Generator#43]
**Describe the bug**
Error: <<set>>: bad evaluation: data.raceTraits[race].genderTraits[gender] is undefined.

**To Reproduce**
Toolbox -> Generate some raiders

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS X 10.13.6
 - Browser Firefox 
 - Version 64.0.2 (64-bit)

**Additional context**

**Comment by Reaver01** [comment]
This is also happening on Google Chrome Version 74.0.3729.108 (Official Build) (64-bit) Windows 10

**Comment by dfreidin** [comment]
I get the same error when I generate a random faction and then click through to the faction:
```
Error: <<set>>: bad evaluation: Cannot read property 'key' of undefined
<<set $currentFaction to $town.factions[$selected.key]>>
```

**Comment by ryceg** [comment]
Closing this issue unless it's still active.
