### ISSUE TITLE
NPC gen ignores race

### ISSUE THREAD

**Issue by Exsulator** [ryceg/Eigengrau-s-Essential-Establishment-Generator#433]
**Describe the bug**

We enter a shop, I want to make a NPC customer of any other race than human. I select a few properties such as woman, young adult, tiefling race (or any race), and click create NPC. But the resulting text describes the NPC as a human, no matter what race I chose (sometimes another random race as well).

**To Reproduce (bugs MUST be replicable)**
Enter any establishment and make a customer of any other race than human, the descriptive text ignores your choice and makes it a human

**Comment by ryceg** [comment]
Hi @Exsulator can you please post *exact* steps to reproduce. We get a lot of bug reports and it is not practical for us to find the bug manually- there might be any number of reasons for a bug to be happening, so knowing exactly what input and data is being used helps us narrow down where to look. I will reopen this when exact steps have been given.

**Comment by Exsulator** [comment]
Enter website https://eigengrausgenerator.com/#yummyleafynoctilio
Click on "The Potion and Abyssal" 
Click on "Customers"
Click on race dropdown, choose "Tiefling"
Click "Create NPC"
You now get a yellow box with info on this newly created NPC.
Read the descriptive text in the yellow box.
BUG: Notice that the race is wrong. Instead of race "tiefling", the race is now "dwarf"
OBSERVATION: Notice that the race dropdown also has changed from tiefling to "half-elf"
OBSERVATION: repro may produce different races than this example
