### ISSUE TITLE
(Feature Request) Coastal Seaport

### ISSUE THREAD

**Issue by romelwell** [ryceg/Eigengrau-s-Essential-Establishment-Generator#434]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The ability to generate a coastal seaport with docks, dockmaster, and associated businesses along the harbor.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ryceg** [comment]
This is already implemented; towns that are generated by a body of water have docks generated. You can force their generation via the create building drop down, or by specifying the generation conditions in the settings (edit biome on restart).
