### ISSUE TITLE
EEE Generator Italian Translation 

### ISSUE THREAD

**Issue by Liunai** [ryceg/Eigengrau-s-Essential-Establishment-Generator#447]

**Comment by ryceg** [comment]
Unfortunately the generator is hardcoded as English, and has a novel's worth of text. It would be a massive undertaking to translate it to any other language.

**Comment by Liunai** [comment]
Hi ryceg, I went for a private message on Reddit, since I could not find any email address to contact you on that, but I see you already answered here... oh well!

Yes, I thought it would have massive hardcoded text... translating it would not be too much of a problem, given enough time (and right now I'm about to spend some holidays at home with little to do, thanks to our friendly pandemic). What I don't know is if it's too much of a hassle for you to copy and "parse" all the text strings in a two (or more) columns form, so that it could be rather easy to match each sentence to its translation.

**Comment by ryceg** [comment]
What I mean is that sentences aren't just straight copy + pasted into the output; there are multiple different sources that come together to construct a sentence, and the grammar of Italian is different enough (from my limited understanding) to make it prohibitive to make any sense. Translating a novel is relatively straight forward, as you have the context all in front of you- this is even more difficult, as it is all broken up into short strings, scattered all over the place. And it is a _lot_ of text.

**Comment by Liunai** [comment]
Got it, alright, it was worth a try! Still, great job!
