### ISSUE TITLE
Edited Town settings not being applied to results.

### ISSUE THREAD

**Issue by Phergus** [ryceg/Eigengrau-s-Essential-Establishment-Generator#45]
**Describe the bug**
Changing a town's government type and clicking on save doesn't persist.

**To Reproduce**
Town Settings:
Select a different government type from the three drop-downs
Click on save.
Town is still has originally generated values.

**Expected behavior**
Expected town to be updated with new government type.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser:  Firefox & Chrome

**Comment by elsidar** [comment]
Seconded; changing economic sliders does not seem to change the existence of the townsfolk.  If they live a "squalid existence", then no values of the economic variables (taxes, welfare, trade, wealth, etc.) will change their "squalid existence."

Occurring on Windows 10, in Firefox.  Unaffected by UBlock Origin.

**Comment by ryceg** [comment]
I'm actively looking into this. Have sorted out the sociopolitics not being changed, wealth is still forthcoming.

**Comment by ryceg** [comment]
I (hopefully) solved this with the 2.2 update. If you still have this issue, please reopen the issue :) Thanks!
