### ISSUE TITLE
"Poisoned Potioner" throws in a tavernless town

### ISSUE THREAD

**Issue by noahlange** [ryceg/Eigengrau-s-Essential-Establishment-Generator#452]
Looks like it's possible for a town to be generated without a tavern; this makes the one-shot generator fail in passage 1.
Additionally, in the description text, the literal string `$adventure.tavern.name` is printed instead of being interpolated with `<<print>>`.

You can list all building types with the following expression in the JS console.

```js
Object.values(window.SugarCube.State.active.variables.town.buildings).map(b => b.type);
```

## To Reproduce

Seed: `evergreenfragrantcavy`

1. Index → Toolbox → "One Shot - The Poisoned Potioner"
2. Error.

**Comment by Glinkis** [comment]
It might be best to never expect a certain building to exist, and only use it if it does.

**Comment by noahlange** [comment]
It specifically being a tavern doesn't appear to be particularly important—in this case, it'd probably be interchangeable with any sort of "slummy" establishment.
