### ISSUE TITLE
Towns I made on 12/15 do not load up at all today when trying to review

### ISSUE THREAD

**Issue by DandDPM** [ryceg/Eigengrau-s-Essential-Establishment-Generator#458]
**Describe the bug**

All buildings previously generated when I put the town together and saved it now read: Error: <<for>>: bad range expression: Cannot read property 'buildings' of undefined

![image](https://user-images.githubusercontent.com/65044691/103158695-9c693200-478e-11eb-8190-3cd3a2649cff.png)

I have loaded all saves and the local save from my computer and they all do it.

Local save file for you to try it yourself: https://www.dropbox.com/s/w89a9zx1xs2v60r/eigengraus-generator-20201215-150633.save?dl=0

**Comment by ryceg** [comment]
Unfortunately saves are not backwards compatible from 2.6 > 2.7. You can, however, download previous versions of the generator from GitHub.
