### ISSUE TITLE
Editing NPCs resets Class, Race, and Backgrounds to top value in dropdown lists, and leaves partner as "undefined".

### ISSUE THREAD

**Issue by elsidar** [ryceg/Eigengrau-s-Essential-Establishment-Generator#46]
**Describe the bug**
Each NPC whose details I've attempted to edit automatically become Male Dragonborn Barbarian Acolytes.  If this data is saved, the hover text descriptions may keep the original race, but other details are changed, and the page with their description shows "Dragonborn" as their race.

Returning to a previous page without saving any changes doesn't affect the Gender, Race, Class, or Background of the NPC.

**To Reproduce**
Town Settings:
Any NPC's Details page
Edit [NPC]

**Expected behavior**
Values for gender, race, class, and background should display as what they were in the generated description that I'm editing.  If I'm editing details for a new NPC who is a female Halfling barmaid, those values should be present in the dropdown lists.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 64.0.2

**Comment by ryceg** [comment]
Ah. Hrm. This is definitely not ideal. Thanks for notifying me about this.
