### ISSUE TITLE
Another option for your exporter

### ISSUE THREAD

**Issue by rvrtex** [ryceg/Eigengrau-s-Essential-Establishment-Generator#480]
**Is your feature request related to a problem? Please describe.**
Add another option for the exporter

**Describe the solution you'd like**
I wanted to try the exporter prior to subscribing and that was not an option. 

**Describe alternatives you've considered**
Anything that is "I am just testing"

**Additional context**

**Comment by ryceg** [comment]
The request is pretty simple- either pay for it, or share it on social media / tell blogs to cover it. If you use the feature but do _not_ do one of those things, then you're directly ignoring the very clear terms of use. 

I'm not going to pretend that some people _aren't_ going to avoid paying- hence the "Paying for things isn't my style" option. But I'm also not interested in giving people a moral out by letting them reason with themselves that they're "just testing"- if you are using the export functionality and you have not abided by the request to respect my wishes that the feature only be used by those who have either payed or shared the generator, I want it to be crystal clear that you're doing the wrong thing.
