### ISSUE TITLE
Everything is giving errors.

### ISSUE THREAD

**Issue by rsage28** [ryceg/Eigengrau-s-Essential-Establishment-Generator#50]
**Describe the bug**
Every description is showing an error instead of the intended text.

**To Reproduce**
Happens on initial page load and after refresh.

**Expected behavior**
Expected standard behavior. 

**Screenshots**
<img width="1183" alt="Screen Shot 2019-04-15 at 9 51 25 AM" src="https://user-images.githubusercontent.com/4007769/56134271-a8827100-5f64-11e9-801f-4db07c7c29a0.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 73

**Additional context**
This is my first time visiting the site. Also, this error is in the console:

`(index):31282 Error: cannot execute macro <<capture>>: Cannot read property 'toLowerCase' of undefined
	<<capture _buildingType, _key, _building>>
	  <<set _building.tooltip = "tip-" + Util.slugify(_building.name) + "-" + Math.floor(Math.random() * 0x10000).toString(16)>>
	  \<<print either("On ", "Along ", "Over on ")>> _building.road is <<if _building.needsWordNoun !== false>>the _building.wordNoun <</if>><span @id="_building.tooltip" class="tip"><<link "_building.name">><<set $selected to {BuildingType: _buildingType, key: _key, building: _building}>><<set $currentPassage to _building>>
	      \<<if settings.showSliders>>
	          \<<goto _building.initPassage>>
	        \<<else>>
	          \<<goto _building.passageName>>
	      \<</if>>
	    \<</link>></span><<run setup.buildingTooltip(_building.tooltip, _building)>><<run setup.tippy(".btn")>>
	\<</capture>>`

**Comment by ryceg** [comment]
Can you please confirm that this persists between restarts (bottom button on the left hand side)?

**Comment by ryceg** [comment]
Closing due to lack of response.
