### ISSUE TITLE
Editing a person doesn't change all references to the person

### ISSUE THREAD

**Issue by JoshSamBob** [ryceg/Eigengrau-s-Essential-Establishment-Generator#503]
**Describe the bug**

When I edit a "person" in a town establishment, the person's name isn't changed everywhere. In some places it's the old name; in others it's new.

**To Reproduce (bugs MUST be replicable)**

[Town Seed](https://eigengrausgenerator.com/#noisyjumpytealpointlessconcerneddrake)

Page to navigate to, buttons to press, etc:

Go to any establishment, pick a person, edit their name. Then go back.

**Additional context**

**Comment by Kerrus** [comment]
Relating to this, editing a person's occupation doesn't propagate properly. Some of the refences change but most don't.
