### ISSUE TITLE
"Weathly man" "belongs to the paupery social class."

### ISSUE THREAD

**Issue by mshall0** [ryceg/Eigengrau-s-Essential-Establishment-Generator#518]
**Describe the bug**

Ecounter's "weatlthy man" entry leads to someone who is described as a pauper (so inconsistent).  In addition some of his background has variable names rather than actual data.

**To Reproduce (bugs MUST be replicable)**

Town Seed = https://eigengrausgenerator.com/#illustriouscompleteichthyostega

On main page I generated a Scenario-- see paste-in below -- note that it provides a link to a "wealthy man."  However when I click that link it takes me to "Josephus Briar" and as part of that page says: "He belongs to the paupery social class. "

so one of these things does not match the other.  Also his sister is a slave and his son is a gongfarmer, so either he is one of the meanest wealthy man ever, or indeed he is a pauper.

Also for early life I get:
I was born on an Inner Plane, and was raised by $currentNPC.familyUnit with my brother. I had upbringing in $currentNPC.familyHome. $currentNPC.childhoodMemories.

Thank you

-----------------------------------

Scenario below
Town Encounter
 — 
It's chilly. The clouds in the sky overhead have a similar resemblance to the scales of a mackerel fish, and it's currently snowing lightly, with a cool breeze carrying the snowflakes a fair distance. The party is mistaken by a **_wealthy man_** as carriage caretakers in a shantytown neighborhood. He hands them money to protect his vehicle. The legitimate caretakers challenge the PCs and try to steal the wealthy wagon. Does the party protect the rich man's vehicle or do they leave the locals to do as they please, risking later persecution by the noble client?

**Comment by ryceg** [comment]
Thanks for this! This is indeed unintended, though I should note that the social class is different to the wealth class; medieval social classes were notoriously immobile. In the case of this person, he would likely be a pauper that came into wealth unexpectedly- but for the Generator's purposes, explicit description takes precedence over what is randomly generated, so we shall put in a flag for the event to ensure that he is generated suitably rich.
