### ISSUE TITLE
Bad evaluationerrors

### ISSUE THREAD

**Issue by craftecode** [ryceg/Eigengrau-s-Essential-Establishment-Generator#53]
Bad evaluation error after clicking on a name link from the main page 
![9D283E1C-B919-4923-BAFC-55DAAF643D08](https://user-images.githubusercontent.com/41639393/56193489-6aa34c80-6039-11e9-9a77-7ba853342b1e.jpeg)
![1D4CFF2B-73D9-4CBB-A30A-59CCE537F30E](https://user-images.githubusercontent.com/41639393/56193490-6b3be300-6039-11e9-9001-ce93307a4931.jpeg)

**Comment by craftecode** [comment]
Error: <<run>>: bad evaluation: undefined is not an object (evaluating 'npc.relationships[targetNPC.key]')
This link for this character was in the friends section of another character.

![78071891-981D-467A-9008-9E0226E8C271](https://user-images.githubusercontent.com/41639393/56194837-6fb5cb00-603c-11e9-8293-b33c0ed6ded1.png)

**Comment by ryceg** [comment]
Thanks, I fixed this issue (hopefully) in the 2.2 update. Please re-open if you come across it again!
