### ISSUE TITLE
Make output print friendly

### ISSUE THREAD

**Issue by nukeduster** [ryceg/Eigengrau-s-Essential-Establishment-Generator#539]
**Is your feature request related to a problem? Please describe.**
It's frusterating to not be able to use this resource offline. We do not use computers at the table.

**Describe the solution you'd like**
Make the webpage output printer-friendly.

**Comment by ryceg** [comment]
Hi @nukeduster, thanks for the feedback. The generator can output to PDF via exporting to use in the online tool GMBinder, as well as use the native Chrome Print to PDF function.
