### ISSUE TITLE
‘Create another question’ created the same question 

### ISSUE THREAD

**Issue by craftecode** [ryceg/Eigengrau-s-Essential-Establishment-Generator#54]
‘Create another question’ created the same question 
 - OS: [e.g. iOS8.1] iPad 12.2
 - Browser [e.g. stock browser, safari] chrome 
 - Version [e.g. 22] 73

![BE154963-D0EF-4561-855E-5FEFF59DB11C](https://user-images.githubusercontent.com/41639393/56193833-3d0ad300-603a-11e9-94b1-fe9c0e723f0b.jpeg)

**Comment by ryceg** [comment]
Did it only create that specific question? If so, that's an issue. Otherwise, it's a 1% chance of happening, and too much code to be worth implementing

**Comment by craftecode** [comment]
Thanks for making this great project! When I pressed the button more it brought up different questions so it must have just been the 1%thing.
