### ISSUE TITLE
Generator does not respect selections when generating NPC (they're always Peasants) 

### ISSUE THREAD

**Issue by Kerrus** [ryceg/Eigengrau-s-Essential-Establishment-Generator#541]
Creating an NPC from within a faction description ignores selections for occupation entirely. 

To reproduce: Go to any faction description and select 'create members'. Enter in any occupation. The resulting NPC is a peasant regardless of what was selected. 

Occasionally the generator will allow you to edit the NPC's description to change their occupation/social status, but most of the time those changes won't propagate to other entries.

**Comment by J05HWA** [comment]
that and Error: <<run>>: bad evaluation: Cannot read property 'members' of undefined. Which shows for all members of guilds that you create. Even the leader
