### ISSUE TITLE
Castle Text Hidden.

### ISSUE THREAD

**Issue by J05HWA** [ryceg/Eigengrau-s-Essential-Establishment-Generator#542]
When I create a castle building the text never appears for it. I have used the inspect tool and can see the text in the <div> tag but it does not appear on the actual page.

To replicate just make a castle building on the town.

![image](https://user-images.githubusercontent.com/80069214/110209025-2fef6b00-7e82-11eb-89d5-cfaa59e8b175.png)

**Comment by ryceg** [comment]
Hi @J05HWA. thanks for this- this is a really weird bug, which I seem to recall encountering many many moons ago... Will have to look into it. Thanks for bringing it to my attention- unsurprisingly with how large the generator is, it's sometimes a little hard to ensure that there aren't any bugs that slip through the cracks.
