### ISSUE TITLE
The second paragraph for the tavern changes every time I go back to the tavern page

### ISSUE THREAD

**Issue by craftecode** [ryceg/Eigengrau-s-Essential-Establishment-Generator#55]
The second paragraph for the tavern changes every time I go back to the tavern page. 
- It said the barmaid was a succubus making good tips
- I clicked on her link to get more info and the page it took me to said she was a human
- I followed a link back to the tavern page and now it says the barmaid is a doppelganger (which I guess would explain the changing form, but it doesn’t seem like it’s intended that way).

![6286E836-B4EB-492C-AFA0-DCBD2252D7F4](https://user-images.githubusercontent.com/41639393/56194524-de465900-603b-11e9-8970-69c21163e338.png)

**Comment by ryceg** [comment]
Thanks for this. I've made a change, and patrons/waitstaff will now persist in 2.1.1
