### ISSUE TITLE
Selecting NPC display error

### ISSUE THREAD

**Issue by sheppe** [ryceg/Eigengrau-s-Essential-Establishment-Generator#556]
**Describe the bug**

Editing my city, then listing buildings and selecting one of the NPCs displays an error. I have sliders turned on.

**To Reproduce (bugs MUST be replicable)**

Town Seed (click [here](https://eigengrausgenerator.com/#respectfulprofuseowl) for info):

Page to navigate to, buttons to press, etc:

From the main city page > Description of Ur Revna > List of Buildings > Darrak Torevir

![image](https://user-images.githubusercontent.com/3595213/112884010-d4c92680-9083-11eb-9331-87b304c62bf7.png)

**Comment by sheppe** [comment]
Here's the save file.
[Uploading eigengraus-generator-20210329-113400.zip…]()

**Comment by sheppe** [comment]
Here's the save file.
[eigengraus-generator-20210329-113400.zip](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/files/6223823/eigengraus-generator-20210329-113400.zip)

**Comment by ryceg** [comment]
Thanks for this- this is an error that has already been identified and fixed.
