### ISSUE TITLE
I can no longer load older saves

### ISSUE THREAD

**Issue by Omn1sc1ent** [ryceg/Eigengrau-s-Essential-Establishment-Generator#56]
**Describe the bug**
When loading older Saves to disk by clicking "Load from Disk..." 

"I receive this error State object has no seed, but PRNG is enabled.

Aborting."
**To Reproduce**
Reload.

**Expected behavior**
To load the older saves.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version current 2.2

**Additional context**
I notated some of the information for one of my towns we have ventured through, but I have lost quite a bit more that could end up being vital.

**Comment by ryceg** [comment]
Unfortunately, PRNG wasn't enabled on earlier builds. This means that 2.1 onwards is incompatible with previous savefiles. If you need to use the save file, you can download any previous version of the generator here: https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/commits/master/docs/index.html
