### ISSUE TITLE
Error when opening the one shot

### ISSUE THREAD

**Issue by andriantimeswift** [ryceg/Eigengrau-s-Essential-Establishment-Generator#560]
**Describe the bug**

When opening the one-shot page, an error appears near the top, which reads: Error: <<set>>: bad evaluation: Cannot convert undefined or null to object

**To Reproduce (bugs MUST be replicable)**

Town Seed (click [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/FAQ#people-keep-talking-about-seeds-what-is-a-seed) for info): #immediatehealthyling

Page to navigate to, buttons to press, etc: Toolbox -> One Shot - The Poisoned Potioner

**Additional context**

I have no idea what this bug means, but I hope reporting it helps you guys out. Leaving the page and returning to it made the error message disappear, but navigating back to it via the Twine navigation buttons revealed it again.

**Comment by ryceg** [comment]
Thanks @andriantimeswift! This has been fixed.
