### ISSUE TITLE
Bug editing factions

### ISSUE THREAD

**Issue by runtotheparty** [ryceg/Eigengrau-s-Essential-Establishment-Generator#566]
**Describe the bug**
Whenever you try and click on the edit faction button on the city the following error is presented:

Motivation:
Error: <<listbox>>: bad evaluation: Cannot read property 'motivation' of undefined
Member's Trait:
Error: <<listbox>>: bad evaluation: Cannot read property 'membersTrait' of undefined
Leadership Type:
Error: <<listbox>>: bad evaluation: Cannot read property 'leader' of undefined
Joining Requirement:
Error: <<listbox>>: bad evaluation: Cannot read property 'joiningRequirement' of undefined
Joining Initiation:
Error: <<listbox>>: bad evaluation: Cannot read property 'joiningInitiation' of undefined

**To Reproduce (bugs MUST be replicable)**
To reproduce, click on the edit faction button

Town Seed (click [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/FAQ#people-keep-talking-about-seeds-what-is-a-seed) for info): #judiciousoffbeatiguana

Page to navigate to, buttons to press, etc:
Edit Faction

**Additional context**
Screenshot attached

![Bug](https://user-images.githubusercontent.com/82223676/114195501-69ffd100-9948-11eb-9009-6d72cf5a8904.png)

**Comment by ryceg** [comment]
Oops, thanks- forgot to finish that.
