### ISSUE TITLE
Life Events are not initialising properly

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#576]
**Describe the bug**

Many of the life events tabs are rendered undefined for some reason.

**To reproduce:** #hatefulcoordinatedgannet > Detailed description > Nipmonger Zork 

![image](https://user-images.githubusercontent.com/36913739/120912230-dbea6180-c6d0-11eb-969c-0dbb177e403f.png)

This has a **$20USD bounty** for being solved, payable via PayPal; help would be much appreciated.

**Comment by Elvanos** [comment]
Is there a repo with an example of this bug being shown so we can reproduce it on our end?

**Comment by ryceg** [comment]
@Elvanos Found the issue- problem was using an `Object.keys` where it should've been `Object.values`! I'll be posting another bounty soon :)
