### ISSUE TITLE
Marketplace switching

### ISSUE THREAD

**Issue by TerryRunders** [ryceg/Eigengrau-s-Essential-Establishment-Generator#58]
**Describe the bug**
Whenever you click through to a character in the marketplace/bazaar, all of the stalls and characters change when you click the built-in back button or follow the breadcrumb back. This makes consistency impossible.

**To Reproduce**
Town Settings:
"The Markets of..." pageSettings of page (Tavern, Blacksmith, etc.)

**Expected behavior**
When I click back, or "The Markets of..." on the breadcrumb I should be taken to the same list of stalls and characters.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: Not sure

**Comment by ryceg** [comment]
Thanks for this, have just sorted out what was going on. This will be fixed in the next update, which I'll push to live now. Shouldn't break compatibility with anything at all.
