### ISSUE TITLE
in Tavern template: Talk with *Proprietor* disappears after you click "What's on offer" and the menu expands

### ISSUE THREAD

**Issue by imiancrook** [ryceg/Eigengrau-s-Essential-Establishment-Generator#580]
**Describe the bug**

Talk with *Proprietor* disappears after you click "What's on offer" and the menu expands

**To Reproduce (bugs MUST be replicable)**

Click on "Whats on offer"

Town Seed (click [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/FAQ#people-keep-talking-about-seeds-what-is-a-seed) for info):
https://eigengrausgenerator.com/#stripedsphericalprawn

Page to navigate to, buttons to press, etc:
Town, Notable buildings, Tavern, "Whats on offer"

**Additional context**

**Comment by imiancrook** [comment]
Sorta disregard, it pushed the content to the left column. Still puts user in a "Wait, whered it go?"

Defintely low priority now.

**Comment by ryceg** [comment]
Thanks for following the issue template. This is a "working as intended" situation, though if other people have the same issue in future I will revisit this.
