### ISSUE TITLE
Market merchandice

### ISSUE THREAD

**Issue by TerryRunders** [ryceg/Eigengrau-s-Essential-Establishment-Generator#59]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
When clicking through to a character description from the Marketplace/Bazaar, a list of the aforementioned merchandise and prices would be useful.

**Comment by ryceg** [comment]
Merchandise is currently an array of random things, and I deliberately left price off so DMs would be able to haggle; for all I know, carrots could be very valuable in the DM's world. If there's sufficient interest, I'll include this.
