### ISSUE TITLE
Generator not working

### ISSUE THREAD

**Issue by JoshSamBob** [ryceg/Eigengrau-s-Essential-Establishment-Generator#591]
**Describe the bug**

The entire generator appears to be broken thanks to the new update.
![image](https://user-images.githubusercontent.com/46507869/115999051-395e9f00-a5b8-11eb-9208-09813709c3f2.png)

**To Reproduce (bugs MUST be replicable)**

Town Seed (click [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/FAQ#people-keep-talking-about-seeds-what-is-a-seed) for info): https://eigengrausgenerator.com/#wretchedbrilliantdeer

Page to navigate to, buttons to press, etc: Just load the page. I get the error above, and the page looks like this:
![image](https://user-images.githubusercontent.com/46507869/115999099-6e6af180-a5b8-11eb-9568-8e52dbca1694.png)

**Additional context**

**Comment by ryceg** [comment]
Hi, please provide information about the browser and OS that you are using, and any extensions that may interfere with the running of scripts.

**Comment by JoshSamBob** [comment]
It was working until the newest update.

This is Windows 10, Google Chrome browser.

Extensions:
Checker Plus for Google Calendar
Contacts+ for Gmail
Google Docs Offline
Grammarly for Chrome
RoboForm Password Manager
Type-ahead-find
Weather

Thanks,
 - Josh

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ryceg** [comment]
Can you please provide the Windows build version and Chrome build version? Have you tried it in another browser? On another device?

**Comment by JoshSamBob** [comment]
Win10 Home, OS build 19041.928
Chrome version 90.0.4430.85 (Official Build) (64-bit)

I rebooted my machine, it's still screwy.

However... I tried it on MS Edge and it works a treat.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
