### ISSUE TITLE
Custom name of town is not used in building names

### ISSUE THREAD

**Issue by Dschaykib** [ryceg/Eigengrau-s-Essential-Establishment-Generator#638]
**Describe the bug**

When setting the town's name to a user-chosen one instead of rolling, the name is not used within the generated text.

**To Reproduce (bugs MUST be replicable)**

Town Seed: #decentevergreenscaup
The original name was _Wasanthistowe_ and NEWTOWN the user-chosen one. It is used at the top, but not within the building names

**Comment by ryceg** [comment]
I'm not able to reproduce this; can you please post a screenshot?

**Comment by Dschaykib** [comment]
Sure:
new link: https://eigengrausgenerator.com/#euphoricbitesizednighthawk
The new custom name is NEWTOWN and the original was "Stenehalas"

screenshot:
<img width="1792" alt="Screenshot 2021-05-31 at 13 05 56" src="https://user-images.githubusercontent.com/26231434/120184216-017af500-c211-11eb-9541-1d0e1c99db33.png">
