### ISSUE TITLE
Duplicate building names

### ISSUE THREAD

**Issue by mpkingsley** [ryceg/Eigengrau-s-Essential-Establishment-Generator#649]
When a new town is generated, there is a fairly high chance of duplicate building names being generated for unique buildings.  In the below example seed, it is **The Town Square**.  Each "Town Square" has conflicting descriptions, and different UUID's

**To Reproduce (bugs MUST be replicable)**

Town Seed (click [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/FAQ#people-keep-talking-about-seeds-what-is-a-seed) for info): sweetadepttarantula

Page to navigate to, buttons to press, etc:

**Additional context**
  I've run across this multiple times, and trying to get an example seed, only had to generate 3 new towns to get a duplicate name.

**Comment by ryceg** [comment]
Working as intended- Town squares do not currently have unique names.
