### ISSUE TITLE
Export to JSON malfunctioning

### ISSUE THREAD

**Issue by toledo932** [ryceg/Eigengrau-s-Essential-Establishment-Generator#652]
**Describe the bug**

When using the export to raw JSON function, the JSON that produced is not readable by standard JSON interpreters. There seems to be something strange in the export format, it ends with a ] instead of a }

**To Reproduce (bugs MUST be replicable)**

Town Seed (https://eigengrausgenerator.com/?seed=decisivewelcomedairycow#OutputEverything):

**Comment by Glinkis** [comment]
Can you attach one of these out Jason files?
And a JSON that starts and ends with square brackets is perfectly valid.
```json
["value"]
```

**Comment by toledo932** [comment]
Sure thing! Here's the string copy pasted into a .txt. 
[town_of_Ockjaw.txt](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/files/6843794/town_of_Ockjaw.txt)


My apologies, i wasn't clear: the JSON as produced starts with a { and ends with a ]. Granted my experience is mostly with python, so I may be missing something, but that seems weird to me.
