### ISSUE TITLE
Demographics bug

### ISSUE THREAD

**Issue by Rinzlers** [ryceg/Eigengrau-s-Essential-Establishment-Generator#659]
I set up a town that was 94% Dwarven and the result was not reflected in the generated result.  
[eigengraus-generator-20210730-200942.zip](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/files/6911646/eigengraus-generator-20210730-200942.zip)

**Comment by ryceg** [comment]
Closing as this is a duplicate of #645
