### ISSUE TITLE
Bad condition expression in <<if>>

### ISSUE THREAD

**Issue by xSpazztic** [ryceg/Eigengrau-s-Essential-Establishment-Generator#663]
Valea Fox is a mid thirties female half-elf. She is medium sized and lean, and has blue eyes with light skin. The most notable physical trait of Valea is that she has widely bowed legs.

Valea is a habitual liar.
**Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'result' of undefined** When she is relaxed, she is cautious. In moments of stress, she becomes murderous. Religion-wise, Valea is a critical student of Demeter.
Perhaps due to sexism, Valea has been somewhat unsuccessful as a butcher, with a background of being a soldier. She belongs to the peasantry social class.
Valea currently has 34 cp and 4 sp in her pockets, and 30 Gold 4 Silver to her name. She lives on Orla Street. Valea knows Common and Elvish.
Valea currently earns 7 Silver 2 Copper per day.

**Comment by ryceg** [comment]
Hi, please provide exact steps to reproduce.
