### ISSUE TITLE
Typo  - UX problem: [UX_PROBLEM]

### ISSUE THREAD

**Issue by xSpazztic** [ryceg/Eigengrau-s-Essential-Establishment-Generator#664]
**Issue**:
Typo
The problem with the user experience.
Iconic Crossbow, Heavy of the Capital
The weapon is inscribed with holy symbols of the God of the DM's choice. A cleric or paladin that serves that god may use this weapon as a divine focus. The bearer gains +1 to intelligence saving **thows**.

**Proposed Solution**:
Change "thows" to "throws".
Proposed method of solving the user experience issue.

**Additional information**:
N/A
Additional information that is needed, such as steps to reproduce, or the town seed.
Generation of a magic item (weapon).

**Comment by ryceg** [comment]
Thanks for this. I have made the change locally and will include it in the next update.
