### ISSUE TITLE
Crypts, Cemeteries, and Mausoleums

### ISSUE THREAD

**Issue by WishingOnAWendy** [ryceg/Eigengrau-s-Essential-Establishment-Generator#68]
The current temples should have a change of generating either a crypt, a cemetery, or a mausoleum that has a small description and a current rumor/historic fact.

The temple page should have a chance of generating one of 3 collapsed links that say explore $temple.name's crypt/cemetery/mausoleum and when clicked on they should generate a small paragraph that includes a short description of the place and then gives a historic fact/rumor about it. For examples of these types of menus look at shipsOutput.twee or brotherOutput.twee

**Comment by Ytnim** [comment]
Should a temple always have a crypt, cemetery or mausoleum, or should there also be a chance to not have any of them?

**Comment by WishingOnAWendy** [comment]
Temples should have a % chance of generating either a crypt, cemetery, mausoleum, or nothing. The largest chance should be for nothing and the smallest should be for a crypt

**Comment by ryceg** [comment]
@WishingOnAWendy are you satisfied with the current graveyard implementation?

**Comment by WishingOnAWendy** [comment]
There's more I'd like to do in the future, but I'm satisfied that it's in a passable and useable state for the time being.
