### ISSUE TITLE
Add Inns as a building type

### ISSUE THREAD

**Issue by kenshin13850** [ryceg/Eigengrau-s-Essential-Establishment-Generator#693]
**Is your feature request related to a problem? Please describe.**
No. I would like inns (and/or other lodging) as a type of building. Tavern is the closest I can find among the current buildings.

**Describe the solution you'd like**
Add inns as a building with an innkeeper NPC.

**Describe alternatives you've considered**
I just use the tavern now and assume they have lodging.

**Comment by ryceg** [comment]
Closing as inns are already part of the generator; accommodation can be found at the bottom of the page.
