### ISSUE TITLE
Export to GM BInder issues with pages and columns

### ISSUE THREAD

**Issue by carterartist** [ryceg/Eigengrau-s-Essential-Establishment-Generator#698]
Export to GM binder hides columns and columns of data, especially the NPC lists and buildings.

https://eigengrausgenerator.com/?seed=majorwoefulgraysquirrel#OutputEverything

**Comment by ryceg** [comment]
Hi, thanks for taking the time to create an issue. Unfortunately this is a known issue that is on GMBinder's end, not ours, and there's nothing that we can do. As stated on the export page; 

> Copy paste the above into a [GMBinder](https://www.gmbinder.com/) document.

>
> You can likely use any .html renderer, but this is optimized for GMBinder. You need to set the document to not use the default GMBinder theme in the document settings in order for it to look like the DMG. **Please note that you will need to add pagebreaks (\pagebreakNum) to ensure that info is not being pushed off the page.**
