### ISSUE TITLE
More female titles for NCPs

### ISSUE THREAD

**Issue by arocsirrachinc** [ryceg/Eigengrau-s-Essential-Establishment-Generator#700]
As I am creating new NCPS for a town, I noticed I could mark a man as a king and prince but not a woman as queen or princess. I'm hoping more titles are presented and that the "how I become a..." generates with the changing in titles. Can you please add this feature?

**Comment by ryceg** [comment]
Thanks for the great idea- I have added this as a pull request for inclusion in the next update.

**Comment by arocsirrachinc** [comment]
Thank you so much for responding. I appreciate it a lot. 😊
