### ISSUE TITLE
Better Code Documentation

### ISSUE THREAD

**Issue by WishingOnAWendy** [ryceg/Eigengrau-s-Essential-Establishment-Generator#72]
Much of the code is completely undocumented or only slightly documented. Instead the code should be well documented with what each files does, what larger functions within the files do and where they are called.
 Should also document what the sentence is for any longer generated strings so people can easily contribute to lists without needing to go anywhere else in the program.

**Comment by ryceg** [comment]
This one's on me... Sorry everyone!

**Comment by ryceg** [comment]
Closing as this is a continual issue, with no defined endpoint.
