### ISSUE TITLE
Add Create New Building button in the town's "detailed description" screen

### ISSUE THREAD

**Issue by poi999** [ryceg/Eigengrau-s-Essential-Establishment-Generator#750]
The "detailed description" screen is a much cleaner way to review the town's buildings compared to the town's "home" screen, yet it lacks the Create New Building button that the latter has. This is esp. surprising since the "detailed description" screen already has a conveniently placed Create New Faction button, and it'd be nice if the building list there had that too.

**Comment by Kalekdan** [comment]
I'd like to take a look at this if possible

**Comment by Kalekdan** [comment]
@ryceg - I believe this issue can be closed now
