### ISSUE TITLE
Renaming and Demographics still broken

### ISSUE THREAD

**Issue by Rinzlers** [ryceg/Eigengrau-s-Essential-Establishment-Generator#752]
**Renaming the town and changing demographics does not work.**

When renaming the town, the title and opening paragraph update, but none of the rest of the references to the town name are updated.  Also when adjusting the demographic sliders no changes occur to the town generated.

**To Reproduce (bugs MUST be replicable)**

Town Seed (click [here](https://eigengrausgenerator.com/?seed=sugarywastefulseal) for info):

**Comment by ryceg** [comment]
Thanks, I'm trying to push out an update soon.
