### ISSUE TITLE
Hovering over "Roll a new town" shifts the banner down by a pixel or two

### ISSUE THREAD

**Issue by rhi-gray** [ryceg/Eigengrau-s-Essential-Establishment-Generator#762]
### Describe the bug

On the landing page, if you hover over the "Roll a new town" button in the top right, the different CSS applied to the element causes the "Eigengrau's Essential Establishment Generator" banner to move down a small amount in Firefox. This is not an ideal user experience.

It's hard to see in the pictures, but very obvious if you have the page open in Firefox:

![Screenshot from 2022-08-27 13-58-00](https://user-images.githubusercontent.com/103016457/187013598-1a1bc82e-b3f4-45a5-907b-3cd63cbceefd.png)
![Screenshot from 2022-08-27 13-58-17](https://user-images.githubusercontent.com/103016457/187013601-34a335a5-5d98-42b6-90e4-7b8de1cc3f15.png)

### To Reproduce (bugs MUST be replicable)

Town Seed (click [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/FAQ#people-keep-talking-about-seeds-what-is-a-seed) for info): any seed

### Page to navigate to, buttons to press, etc:

Go to the landing page and open any town. Hover over "Roll a new town". The banner will shift down a small amount when you are hovering over "Roll a new town", then return to its original place when you move away.

### Additional context

This affects Firefox, but does not seem to affect Google Chrome. It's probably something to do with the `.restart` and `.restart:hover` CSS rules. Looking at the differences between how `padding` vs `margin` vs `border` change element positions would be a good place to start.

**Comment by Kalekdan** [comment]
I will take a look at this - worth noting that this does not occur in the live version (https://eigengrausgenerator.com/)
