### ISSUE TITLE
Implement detailed family history

### ISSUE THREAD

**Issue by WishingOnAWendy** [ryceg/Eigengrau-s-Essential-Establishment-Generator#77]
Expand on history within families to create more cohesive family webs and pasts. This could include a family trade, the social dynamic between family members, or the addition of other family such as uncles, cousins, or grandparents

**Comment by ryceg** [comment]
The function for the creation of family members has already been done, but is not currently implemented outside of one or two cases. On top of this, family history is currently _very_ fragmented; children of the same parents can have different numbers of siblings, and have totally different histories. Some semblance of continuity is needed.

**Comment by ever-3W** [comment]
Currently in progress of a significant rework to family trees.
Now transitioning life events, etc. to use the new generators

**Comment by ever-3W** [comment]
![Screenshot from 2019-06-05 23-18-18](https://user-images.githubusercontent.com/42660111/59006581-60573080-87e8-11e9-90ab-ac3f1db0c618.png)

**Comment by ryceg** [comment]
@ever-3W are you satisfied with the implementation? Shall this be closed?

**Comment by WishingOnAWendy** [comment]
Does this need to be open still? Are we going to implement things like a family trade or anything like that or is this sufficient?

**Comment by ryceg** [comment]
I suspect that this is sufficient for now; we have family social class, so it's not totally inconsistent.
