### ISSUE TITLE
Town Chaos

### ISSUE THREAD

**Issue by WishingOnAWendy** [ryceg/Eigengrau-s-Essential-Establishment-Generator#78]
How likely the town is to be a hive of scum and villainy. Calculate the town's potential chaos factor based on size, wealth, and politics. 
Use the level town chaos to make decisions on NPC, event, and building generation

**Comment by ryceg** [comment]
town.roll.sin has already been initialised, but needs to be more closely tied with the politics and wealth of the town; specifically, things like kleptocracies should be far more chaotic.
