### ISSUE TITLE
Fletcher Creation

### ISSUE THREAD

**Issue by WishingOnAWendy** [ryceg/Eigengrau-s-Essential-Establishment-Generator#80]
Create a new Micro Establishment for a Fletcher inside of goodsAndServices.js using the existing Bakery template.

These buildings should have at least 3 items for sale, at least 5 choices in each list and be fleshed out enough that others could easily contribute to the random lists at a later date.

**Comment by underdorff18** [comment]
This would be my first time contributing, but I'm interested in helping. By fletcher do you mean a shop just for arrows, or bows as well?

**Comment by WishingOnAWendy** [comment]
Both would be preferable but the potential to sell only one or the other would add some flair!
