### ISSUE TITLE
Replace var with let and const

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#88]
`let` is for variables and can be reassigned.
`const` is for values.

`var` is the weakest, and should be phased out. A find and replace would involve squashing every single error, though, so this is more of a gradual process, I suppose, unless somebody wants to spend an afternoon recompiling and replacing each `const` that complains with a `let`.

**Comment by cktang88** [comment]
Maybe replace each `var` with `let` for the time being, and then use `const` later on as appropriate?

**Comment by monsagri** [comment]
This should be quite easy to handle if you set up a linter that lets you use autocorrect, I've created an issue about setting up a project wide linter which might warrant some discussion about rules you want to enforce?

**Comment by Glinkis** [comment]
This can be closed, as we now enforce this with eslint.
