### ISSUE TITLE
Redo the loading screen and have it display console.log

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#89]
Currently, the loading screen is stock standard Twine. A reskin would help the Generator's identity.

**Comment by ryceg** [comment]
ChapelR has done a great custom loading screen.

https://github.com/ChapelR/spellbook-source/blob/master/src/css/loader.css

**Comment by WishingOnAWendy** [comment]
Is this necessary still since we are about to move away from Twine?
