### ISSUE TITLE
Eliminate dependencies

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#90]
Removing `tippy.js` from head content and adding the `tippy.min.js` file would mean that the only call 'home' would be Google Analytics. Great for privacy, and this will also help with Google Analytics, as it currently gets a janky version when testing compatibility with mobile.

**Comment by cktang88** [comment]
by `tippy.min.js` do you mean https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/blob/master/tippy.all.min.js

**Comment by Glinkis** [comment]
It's *usually* awkward to store dependencies and minified files in git, and should be avoided if possible.

**Comment by ryceg** [comment]
Ohhh. I see. That's disappointing! Thanks for the heads up.
