### ISSUE TITLE
Create a changelog

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#97]
Make a changelog.

**Comment by Glinkis** [comment]
From what I can see, there already exists a changelog under `Meta/ChangelogFull.twee`.

**Comment by WishingOnAWendy** [comment]
> From what I can see, there is already one available under `Meta/ChangelogFull.twee`.

I could be wrong but I believe this is for a simple .txt changelog as that one is explicitly for outward presentation within the generator with Tippy messages and only gives a general overview of things
